import { PrismaClient } from '@prisma/client';
import { DemoContext } from './index';

export async function seedEvidence(prisma: PrismaClient, ctx: DemoContext): Promise<void> {
  const now = new Date();
  const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000);
  const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000);

  // ==========================================
  // 20 Evidence Records
  // ==========================================

  const evidenceData = [
    {
      evidenceRef: 'EVD-2025-0001',
      title: 'ISO 27001 Certificate - BSI Group',
      evidenceType: 'CERTIFICATE' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Certification',
      fileName: 'iso27001-certificate-2024.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 245000,
      sourceType: 'VENDOR_PROVIDED' as const,
      validFrom: daysAgo(340),
      validUntil: daysFromNow(190),
      collectedAt: daysAgo(340),
      collectedById: ctx.users.ismsManager,
      reviewedAt: daysAgo(338),
      reviewedById: ctx.users.ciso,
      approvedAt: daysAgo(338),
      approvedById: ctx.users.ciso,
      tags: ['iso27001', 'certification', 'bsi'],
      description: 'ISO 27001:2022 certificate issued by BSI Group following successful certification audit.',
    },
    {
      evidenceRef: 'EVD-2025-0002',
      title: 'Q4 2025 Vulnerability Scan Report',
      evidenceType: 'REPORT' as const,
      status: 'APPROVED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Vulnerability Management',
      fileName: 'vuln-scan-q4-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 1200000,
      sourceType: 'AUTOMATED' as const,
      validFrom: daysAgo(90),
      validUntil: daysFromNow(0),
      collectedAt: daysAgo(90),
      collectedById: ctx.users.securityLead,
      reviewedAt: daysAgo(88),
      reviewedById: ctx.users.ciso,
      approvedAt: daysAgo(87),
      approvedById: ctx.users.ciso,
      tags: ['vulnerability', 'scan', 'quarterly'],
      description: 'Quarterly vulnerability scan results covering all production systems.',
    },
    {
      evidenceRef: 'EVD-2025-0003',
      title: 'Security Awareness Training Completion Report',
      evidenceType: 'REPORT' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Training',
      fileName: 'training-completion-q4-2025.xlsx',
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      fileSizeBytes: 85000,
      sourceType: 'MANUAL_UPLOAD' as const,
      validFrom: daysAgo(60),
      validUntil: daysFromNow(30),
      collectedAt: daysAgo(60),
      collectedById: ctx.users.ismsManager,
      approvedAt: daysAgo(58),
      approvedById: ctx.users.ciso,
      tags: ['training', 'awareness', 'completion'],
      description: 'Q4 2025 security awareness training completion rates by department.',
    },
    {
      evidenceRef: 'EVD-2025-0004',
      title: 'Penetration Test Report - Payment Gateway',
      evidenceType: 'REPORT' as const,
      status: 'APPROVED' as const,
      classification: 'RESTRICTED' as const,
      category: 'Security Testing',
      fileName: 'pentest-payment-gw-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 3200000,
      sourceType: 'VENDOR_PROVIDED' as const,
      validFrom: daysAgo(120),
      validUntil: daysFromNow(245),
      collectedAt: daysAgo(120),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(115),
      approvedById: ctx.users.ciso,
      tags: ['pentest', 'payment-gateway', 'annual'],
      description: 'Annual penetration test conducted by external assessor covering payment gateway application.',
    },
    {
      evidenceRef: 'EVD-2025-0005',
      title: 'Access Review - Payment Systems Q4',
      evidenceType: 'DOCUMENT' as const,
      status: 'APPROVED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Access Control',
      fileName: 'access-review-payment-q4-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 156000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(45),
      collectedById: ctx.users.ismsManager,
      approvedAt: daysAgo(42),
      approvedById: ctx.users.ciso,
      tags: ['access-review', 'quarterly', 'payment'],
      description: 'Quarterly access review for payment processing systems with manager sign-off.',
    },
    {
      evidenceRef: 'EVD-2025-0006',
      title: 'BCP Test Results - November 2025',
      evidenceType: 'TEST_RESULT' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Business Continuity',
      fileName: 'bcp-test-results-nov2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 420000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(100),
      collectedById: ctx.users.ismsManager,
      approvedAt: daysAgo(95),
      approvedById: ctx.users.admin,
      tags: ['bcp', 'test', 'annual'],
      description: 'Annual business continuity plan test results including failover drill.',
    },
    {
      evidenceRef: 'EVD-2025-0007',
      title: 'SIEM Log Retention Configuration',
      evidenceType: 'CONFIGURATION' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Logging',
      fileName: 'siem-retention-config.json',
      mimeType: 'application/json',
      fileSizeBytes: 12000,
      sourceType: 'AUTOMATED' as const,
      collectedAt: daysAgo(30),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(28),
      approvedById: ctx.users.ciso,
      tags: ['siem', 'logging', 'configuration'],
      description: 'Datadog SIEM log retention configuration showing 12-month retention for security logs.',
    },
    {
      evidenceRef: 'EVD-2025-0008',
      title: 'Firewall Rule Review - Dublin',
      evidenceType: 'DOCUMENT' as const,
      status: 'APPROVED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Network Security',
      fileName: 'firewall-review-dublin-q4.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 280000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(50),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(47),
      approvedById: ctx.users.ciso,
      tags: ['firewall', 'review', 'dublin'],
      description: 'Quarterly firewall rule review for Dublin HQ network perimeter.',
    },
    {
      evidenceRef: 'EVD-2026-0001',
      title: 'PCI DSS Compliance Scan - January 2026',
      evidenceType: 'SCAN_RESULT' as const,
      status: 'APPROVED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Compliance',
      fileName: 'pci-scan-jan2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 890000,
      sourceType: 'AUTOMATED' as const,
      collectedAt: daysAgo(25),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(22),
      approvedById: ctx.users.ciso,
      tags: ['pci', 'compliance', 'scan'],
      description: 'Monthly PCI DSS ASV scan results for cardholder data environment.',
    },
    {
      evidenceRef: 'EVD-2026-0002',
      title: 'Encryption Key Rotation Log',
      evidenceType: 'LOG' as const,
      status: 'APPROVED' as const,
      classification: 'RESTRICTED' as const,
      category: 'Cryptography',
      fileName: 'key-rotation-log-jan2026.csv',
      mimeType: 'text/csv',
      fileSizeBytes: 45000,
      sourceType: 'AUTOMATED' as const,
      collectedAt: daysAgo(20),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(18),
      approvedById: ctx.users.ciso,
      tags: ['encryption', 'key-rotation', 'monthly'],
      description: 'Monthly encryption key rotation audit log from AWS KMS.',
    },
    {
      evidenceRef: 'EVD-2026-0003',
      title: 'Vendor Risk Assessment - Stripe 2026',
      evidenceType: 'ASSESSMENT_RESULT' as const,
      status: 'APPROVED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Vendor Management',
      fileName: 'vendor-assessment-stripe-2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 520000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(35),
      collectedById: ctx.users.riskAnalyst,
      approvedAt: daysAgo(30),
      approvedById: ctx.users.ciso,
      tags: ['vendor', 'risk-assessment', 'stripe'],
      description: 'Annual vendor risk assessment for Stripe payment processing partnership.',
    },
    {
      evidenceRef: 'EVD-2026-0004',
      title: 'ISMS Management Review Minutes - Q4 2025',
      evidenceType: 'MEETING_NOTES' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Governance',
      fileName: 'mgmt-review-q4-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 180000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(40),
      collectedById: ctx.users.ismsManager,
      approvedAt: daysAgo(38),
      approvedById: ctx.users.admin,
      tags: ['management-review', 'isms', 'quarterly'],
      description: 'ISMS Steering Committee Q4 2025 management review meeting minutes.',
    },
    {
      evidenceRef: 'EVD-2026-0005',
      title: 'Endpoint Protection Coverage Report',
      evidenceType: 'REPORT' as const,
      status: 'PENDING' as const,
      classification: 'INTERNAL' as const,
      category: 'Endpoint Security',
      fileName: 'endpoint-coverage-feb2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 340000,
      sourceType: 'AUTOMATED' as const,
      collectedAt: daysAgo(5),
      collectedById: ctx.users.securityLead,
      tags: ['endpoint', 'protection', 'coverage'],
      description: 'Monthly endpoint protection deployment and coverage status report.',
    },
    {
      evidenceRef: 'EVD-2026-0006',
      title: 'Change Advisory Board Minutes - Feb 2026',
      evidenceType: 'MEETING_NOTES' as const,
      status: 'PENDING' as const,
      classification: 'INTERNAL' as const,
      category: 'Change Management',
      fileName: 'cab-minutes-feb2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 95000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(3),
      collectedById: ctx.users.ismsManager,
      tags: ['cab', 'change-management', 'minutes'],
      description: 'Change Advisory Board meeting minutes for February 2026 session.',
    },
    {
      evidenceRef: 'EVD-2026-0007',
      title: 'DORA ICT Risk Assessment',
      evidenceType: 'ASSESSMENT_RESULT' as const,
      status: 'UNDER_REVIEW' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Regulatory',
      fileName: 'dora-ict-risk-assessment-2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 1500000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(10),
      collectedById: ctx.users.complianceOfficer,
      reviewedAt: daysAgo(7),
      reviewedById: ctx.users.ciso,
      tags: ['dora', 'ict', 'risk-assessment'],
      description: 'DORA Article 6 ICT risk management framework assessment.',
    },
    {
      evidenceRef: 'EVD-2026-0008',
      title: 'NIS2 Gap Analysis Report',
      evidenceType: 'REPORT' as const,
      status: 'UNDER_REVIEW' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'Regulatory',
      fileName: 'nis2-gap-analysis-2026.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 2100000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(12),
      collectedById: ctx.users.complianceOfficer,
      tags: ['nis2', 'gap-analysis', 'compliance'],
      description: 'NIS2 Directive compliance gap analysis for ClearStream Payments.',
    },
    {
      evidenceRef: 'EVD-2025-0009',
      title: 'AWS SOC 2 Type II Report',
      evidenceType: 'AUDIT_REPORT' as const,
      status: 'APPROVED' as const,
      classification: 'RESTRICTED' as const,
      category: 'Vendor Compliance',
      fileName: 'aws-soc2-type2-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 4500000,
      sourceType: 'VENDOR_PROVIDED' as const,
      validFrom: daysAgo(200),
      validUntil: daysFromNow(165),
      collectedAt: daysAgo(200),
      collectedById: ctx.users.riskAnalyst,
      approvedAt: daysAgo(195),
      approvedById: ctx.users.ciso,
      tags: ['aws', 'soc2', 'vendor-compliance'],
      description: 'AWS SOC 2 Type II audit report for ClearStream account assessment.',
    },
    {
      evidenceRef: 'EVD-2025-0010',
      title: 'Background Check Policy Compliance',
      evidenceType: 'DOCUMENT' as const,
      status: 'EXPIRED' as const,
      classification: 'CONFIDENTIAL' as const,
      category: 'HR Security',
      fileName: 'bg-check-compliance-h1-2025.pdf',
      mimeType: 'application/pdf',
      fileSizeBytes: 120000,
      sourceType: 'MANUAL_UPLOAD' as const,
      validFrom: daysAgo(300),
      validUntil: daysAgo(120),
      collectedAt: daysAgo(300),
      collectedById: ctx.users.ismsManager,
      approvedAt: daysAgo(298),
      approvedById: ctx.users.ciso,
      tags: ['background-check', 'hr', 'compliance'],
      description: 'H1 2025 background check completion report - now expired, H2 report pending.',
      renewalRequired: true,
      renewalReminderDays: 30,
    },
    {
      evidenceRef: 'EVD-2026-0009',
      title: 'TLS 1.3 Migration Completion Evidence',
      evidenceType: 'SCREENSHOT' as const,
      status: 'APPROVED' as const,
      classification: 'INTERNAL' as const,
      category: 'Change Management',
      fileName: 'tls13-migration-evidence.png',
      mimeType: 'image/png',
      fileSizeBytes: 2800000,
      sourceType: 'MANUAL_UPLOAD' as const,
      collectedAt: daysAgo(28),
      collectedById: ctx.users.securityLead,
      approvedAt: daysAgo(26),
      approvedById: ctx.users.ciso,
      tags: ['tls', 'migration', 'change'],
      description: 'Screenshot evidence of TLS 1.3 configuration across all payment endpoints.',
    },
    {
      evidenceRef: 'EVD-2026-0010',
      title: 'Okta MFA Enforcement Report',
      evidenceType: 'CONFIGURATION' as const,
      status: 'PENDING' as const,
      classification: 'INTERNAL' as const,
      category: 'Access Control',
      fileName: 'okta-mfa-report-feb2026.json',
      mimeType: 'application/json',
      fileSizeBytes: 28000,
      sourceType: 'AUTOMATED' as const,
      collectedAt: daysAgo(2),
      collectedById: ctx.users.securityLead,
      tags: ['okta', 'mfa', 'access-control'],
      description: 'Okta MFA enforcement status across all ClearStream applications.',
    },
  ];

  const evidenceRecords: Record<string, string> = {};

  for (const evd of evidenceData) {
    const record = await prisma.evidence.create({
      data: {
        evidenceRef: evd.evidenceRef,
        title: evd.title,
        description: evd.description,
        evidenceType: evd.evidenceType,
        status: evd.status,
        classification: evd.classification,
        category: evd.category,
        fileName: evd.fileName,
        originalFileName: evd.fileName,
        mimeType: evd.mimeType,
        fileSizeBytes: evd.fileSizeBytes,
        sourceType: evd.sourceType,
        tags: evd.tags,
        validFrom: evd.validFrom,
        validUntil: evd.validUntil,
        collectedAt: evd.collectedAt,
        collectedById: evd.collectedById,
        reviewedAt: evd.reviewedAt,
        reviewedById: evd.reviewedById,
        approvedAt: evd.approvedAt,
        approvedById: evd.approvedById,
        renewalRequired: evd.renewalRequired ?? false,
        renewalReminderDays: evd.renewalReminderDays,
        createdById: evd.collectedById,
      },
    });
    evidenceRecords[evd.evidenceRef] = record.id;
  }

  // Copy evidence IDs to context for cross-linking in seed-relationships
  Object.assign(ctx.evidenceIds, evidenceRecords);

  console.log('    20 evidence records created');

  // ==========================================
  // Link evidence to controls
  // ==========================================
  const controlEvidenceLinks = [
    { evidenceRef: 'EVD-2025-0002', controlId: '8.8', linkType: 'operating' },
    { evidenceRef: 'EVD-2025-0003', controlId: '6.3', linkType: 'operating' },
    { evidenceRef: 'EVD-2025-0004', controlId: '8.29', linkType: 'operating' },
    { evidenceRef: 'EVD-2025-0005', controlId: '5.15', linkType: 'operating' },
    { evidenceRef: 'EVD-2025-0007', controlId: '8.15', linkType: 'implementation' },
    { evidenceRef: 'EVD-2025-0008', controlId: '8.20', linkType: 'operating' },
    { evidenceRef: 'EVD-2026-0001', controlId: '8.24', linkType: 'operating' },
    { evidenceRef: 'EVD-2026-0002', controlId: '8.24', linkType: 'operating' },
    { evidenceRef: 'EVD-2026-0009', controlId: '8.24', linkType: 'implementation' },
    { evidenceRef: 'EVD-2026-0010', controlId: '8.5', linkType: 'operating' },
  ];

  for (const link of controlEvidenceLinks) {
    const controlDbId = ctx.controlIds[link.controlId];
    if (controlDbId && evidenceRecords[link.evidenceRef]) {
      await prisma.evidenceControl.create({
        data: {
          evidenceId: evidenceRecords[link.evidenceRef]!,
          controlId: controlDbId,
          linkType: link.linkType,
          createdById: ctx.users.ciso,
        },
      });
    }
  }

  console.log('    10 evidence-control links created');

  // ==========================================
  // 3 Evidence Requests
  // ==========================================

  // Request 1: Open
  await prisma.evidenceRequest.create({
    data: {
      requestRef: 'REQ-2026-001',
      title: 'H2 2025 Background Check Completion Report',
      description: 'Please provide the H2 2025 background check completion report for all new hires and contractors. This is needed to evidence compliance with A.6.1 Screening control.',
      evidenceType: 'DOCUMENT',
      requiredFormat: 'PDF',
      acceptanceCriteria: 'Report must include all hires from July-December 2025 with verification status.',
      priority: 'HIGH',
      status: 'OPEN',
      requestedById: ctx.users.ismsManager,
      assignedToId: ctx.users.dpo,
      dueDate: daysFromNow(14),
      contextType: 'Control',
      contextRef: 'A.6.1',
      createdById: ctx.users.ismsManager,
    },
  });

  // Request 2: In Progress
  await prisma.evidenceRequest.create({
    data: {
      requestRef: 'REQ-2026-002',
      title: 'Datadog SIEM Alert Configuration Export',
      description: 'Export the current SIEM alert rules and correlation policies from Datadog for the ISO 27001 A.8.16 monitoring control evidence.',
      evidenceType: 'CONFIGURATION',
      requiredFormat: 'JSON or PDF',
      priority: 'MEDIUM',
      status: 'IN_PROGRESS',
      requestedById: ctx.users.complianceOfficer,
      assignedToId: ctx.users.securityLead,
      dueDate: daysFromNow(7),
      contextType: 'Control',
      contextRef: 'A.8.16',
      createdById: ctx.users.complianceOfficer,
    },
  });

  // Request 3: Completed
  const completedRequest = await prisma.evidenceRequest.create({
    data: {
      requestRef: 'REQ-2026-003',
      title: 'TLS Configuration Evidence for CHG-2026-001',
      description: 'Provide evidence of TLS 1.3 configuration across all payment API endpoints following the TLS migration change.',
      evidenceType: 'SCREENSHOT',
      priority: 'HIGH',
      status: 'ACCEPTED',
      requestedById: ctx.users.complianceOfficer,
      assignedToId: ctx.users.securityLead,
      dueDate: daysAgo(25),
      submittedAt: daysAgo(27),
      acceptedAt: daysAgo(25),
      contextType: 'Change',
      contextRef: 'CHG-2026-001',
      createdById: ctx.users.complianceOfficer,
    },
  });

  // Link fulfilled evidence
  if (evidenceRecords['EVD-2026-0009']) {
    await prisma.evidenceRequestFulfillment.create({
      data: {
        requestId: completedRequest.id,
        evidenceId: evidenceRecords['EVD-2026-0009']!,
        notes: 'TLS 1.3 migration screenshots showing all endpoints configured.',
        submittedById: ctx.users.securityLead,
      },
    });
  }

  console.log('    3 evidence requests created');
}
