import { PrismaService } from '../../prisma/prisma.service';
import { PolicyDocumentService } from '../../policies/services/policy-document.service';
import { DocumentExceptionService } from '../../policies/services/document-exception.service';
import { ChangeRequestService } from '../../policies/services/change-request.service';
import { ExecutorMap, prepareCreatePayload, stripMcpMeta } from './types';
import {
  validatePayload,
  CreatePolicyPayload,
  UpdatePolicyPayload,
  PolicyDocumentIdPayload,
  CreatePolicyExceptionPayload,
  ApprovePolicyExceptionPayload,
  CreatePolicyChangeRequestPayload,
} from './payload-schemas';

export interface PolicyExecutorServices {
  policyDocumentService: PolicyDocumentService;
  documentExceptionService: DocumentExceptionService;
  changeRequestService: ChangeRequestService;
  prismaService: PrismaService;
}

export function registerPolicyExecutors(executors: ExecutorMap, services: PolicyExecutorServices): void {
  const { policyDocumentService, documentExceptionService, changeRequestService, prismaService } = services;

  // --- Policy CRUD ---

  executors.set('CREATE_POLICY', async (p, userId) => {
    const validated = validatePayload(CreatePolicyPayload, p, 'CREATE_POLICY');

    // Extract ISO 27001 generator fields before prepareCreatePayload strips them
    const controlMappings = validated['controlMappings'] as
      | { controlId: string; mappingType?: string; coverage?: string }[]
      | undefined;
    const riskMappings = validated['riskMappings'] as
      | { riskId: string; relationshipType?: string }[]
      | undefined;
    const versionInfo = validated['version'] as string | undefined;

    // Remove generator-only fields so prepareCreatePayload doesn't pass them to Prisma
    const rest = { ...validated };
    delete rest['controlMappings'];
    delete rest['riskMappings'];

    const document = await policyDocumentService.create(
      prepareCreatePayload(rest, { relationalOrg: true }) as any,
      userId,
    );

    // Create control mappings if provided (ISO 27001 generator)
    if (controlMappings?.length) {
      await prismaService.documentControlMapping.createMany({
        data: controlMappings.map((m) => ({
          documentId: document.id,
          controlId: m.controlId,
          mappingType: (m.mappingType ?? 'IMPLEMENTS') as any,
          coverage: (m.coverage ?? 'FULL') as any,
          createdById: userId,
        })),
        skipDuplicates: true,
      });
    }

    // Create risk mappings if provided (ISO 27001 generator)
    if (riskMappings?.length) {
      await prismaService.documentRiskMapping.createMany({
        data: riskMappings.map((m) => ({
          documentId: document.id,
          riskId: m.riskId,
          relationshipType: (m.relationshipType ?? 'MITIGATES') as any,
          createdById: userId,
        })),
        skipDuplicates: true,
      });
    }

    // Create initial version record if version info provided (ISO 27001 generator)
    if (versionInfo) {
      const parts = versionInfo.split('.');
      const major = parseInt(parts[0] ?? '1', 10);
      const minor = parseInt(parts[1] ?? '0', 10);
      await prismaService.documentVersion.create({
        data: {
          documentId: document.id,
          version: versionInfo,
          majorVersion: major,
          minorVersion: minor,
          content: document.content ?? '',
          changeType: 'INITIAL',
          changeDescription: `Initial version generated by ISO 27001 Documentation Generator`,
          createdById: userId,
        },
      });
    }

    return document;
  });

  executors.set('UPDATE_POLICY', (p, userId) => {
    const { documentId, ...rest } = validatePayload(UpdatePolicyPayload, p, 'UPDATE_POLICY');
    return policyDocumentService.update(documentId, stripMcpMeta(rest) as any, userId);
  });

  // --- Policy lifecycle (all via updateStatus) ---

  executors.set('SUBMIT_POLICY_REVIEW', (p, userId) => {
    const validated = validatePayload(PolicyDocumentIdPayload, p, 'SUBMIT_POLICY_REVIEW');
    return policyDocumentService.updateStatus(validated.documentId, 'PENDING_REVIEW' as any, userId);
  });

  executors.set('APPROVE_POLICY', (p, userId) => {
    const validated = validatePayload(PolicyDocumentIdPayload, p, 'APPROVE_POLICY');
    return policyDocumentService.updateStatus(validated.documentId, 'APPROVED' as any, userId);
  });

  executors.set('PUBLISH_POLICY', (p, userId) => {
    const validated = validatePayload(PolicyDocumentIdPayload, p, 'PUBLISH_POLICY');
    return policyDocumentService.updateStatus(validated.documentId, 'PUBLISHED' as any, userId);
  });

  executors.set('RETIRE_POLICY', (p, userId) => {
    const validated = validatePayload(PolicyDocumentIdPayload, p, 'RETIRE_POLICY');
    return policyDocumentService.updateStatus(validated.documentId, 'RETIRED' as any, userId);
  });

  // --- Exceptions ---

  executors.set('CREATE_POLICY_EXCEPTION', (p, userId) => {
    const validated = validatePayload(CreatePolicyExceptionPayload, p, 'CREATE_POLICY_EXCEPTION');
    return documentExceptionService.create({
      ...prepareCreatePayload(validated),
      requestedById: userId,
      expiryDate: validated.expiryDate ? new Date(validated.expiryDate) : undefined,
      startDate: validated.startDate ? new Date(validated.startDate) : undefined,
    } as any);
  });

  executors.set('APPROVE_POLICY_EXCEPTION', (p, userId) => {
    const validated = validatePayload(ApprovePolicyExceptionPayload, p, 'APPROVE_POLICY_EXCEPTION');
    return documentExceptionService.approve(validated.exceptionId, {
      approvedById: userId,
      approvalComments: validated.approvalComments,
    });
  });

  // --- Change Requests ---

  executors.set('CREATE_POLICY_CHANGE_REQUEST', (p, userId) => {
    const validated = validatePayload(CreatePolicyChangeRequestPayload, p, 'CREATE_POLICY_CHANGE_REQUEST');
    return changeRequestService.create({
      ...prepareCreatePayload(validated),
      requestedById: userId,
      targetDate: validated.targetDate ? new Date(validated.targetDate) : undefined,
    } as any);
  });
}
