import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Demo data seed (ClearStream Payments)
import { seedDemo } from './seed/demo/index';

async function main() {
  console.log('🌱 Starting database seed...');

  // Create test users
  const passwordHash = await bcrypt.hash('password123', 10);
  
  const users = await Promise.all([
    prisma.user.upsert({
      where: { email: 'admin@riskready.com' },
      update: {},
      create: {
        email: 'admin@riskready.com',
        passwordHash,
        firstName: 'Admin',
        lastName: 'User',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'admin@local.test' },
      update: {},
      create: {
        email: 'admin@local.test',
        passwordHash,
        firstName: 'Local',
        lastName: 'Admin',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'john.smith@riskready.com' },
      update: {},
      create: {
        email: 'john.smith@riskready.com',
        passwordHash,
        firstName: 'John',
        lastName: 'Smith',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'sarah.jones@riskready.com' },
      update: {},
      create: {
        email: 'sarah.jones@riskready.com',
        passwordHash,
        firstName: 'Sarah',
        lastName: 'Jones',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'mike.wilson@riskready.com' },
      update: {},
      create: {
        email: 'mike.wilson@riskready.com',
        passwordHash,
        firstName: 'Mike',
        lastName: 'Wilson',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { email: 'emma.brown@riskready.com' },
      update: {},
      create: {
        email: 'emma.brown@riskready.com',
        passwordHash,
        firstName: 'Emma',
        lastName: 'Brown',
        isActive: true,
      },
    }),
  ]);

  console.log(`✅ Created ${users.length} users`);

  // Guard: skip Acme seed if org already exists (idempotent re-run)
  const existingAcme = await prisma.organisationProfile.findFirst({
    where: { name: 'Acme Corporation' },
  });
  if (existingAcme) {
    console.log('⏭️  Acme data already exists, skipping to demo seed...');
    await seedDemo();
    console.log('\n🎉 Database seed completed successfully!');
    return;
  }

  // Create Organisation Profile
  const orgProfile = await prisma.organisationProfile.create({
    data: {
      name: 'Acme Corporation',
      legalName: 'Acme Corporation Ltd.',
      description: 'A leading technology company specializing in enterprise software solutions.',
      industrySector: 'technology',
      industrySubsector: 'Enterprise Software',
      marketPosition: 'market_leader',
      employeeCount: 250,
      size: 'medium',
      annualRevenue: 50000000,
      revenueCurrency: 'USD',
      revenueTrend: 'growing',
      headquartersAddress: '123 Tech Park, Silicon Valley, CA 94025',
      registeredAddress: '123 Tech Park, Suite 100, San Francisco, CA 94025, USA',
      contactEmail: 'info@acme.com',
      contactPhone: '+1 (555) 123-4567',
      website: 'https://www.acme.com',
      foundedYear: 2015,
      registrationNumber: 'C4567890',
      taxIdentification: '12-3456789',
      dunsNumber: '123456789',
      leiCode: '5493001KJTIIGC8Y1R12',
      stockSymbol: 'ACME',
      naceCode: '62.01',
      sicCode: '7372',
      parentOrganization: null,
      primaryCompetitors: ['TechCorp', 'InnoSoft', 'DataSystems Inc'],
      operatingCountries: ['United States', 'United Kingdom', 'Germany', 'Singapore', 'Australia'],
      revenueStreams: ['Software Licenses', 'SaaS Subscriptions', 'Professional Services', 'Support Contracts'],
      fiscalYearStart: '01-01',
      fiscalYearEnd: new Date('2024-12-31'),
      reportingCurrency: 'USD',
      employeeGrowthRate: 15,
      remoteWorkPercentage: 40,
      missionStatement: 'To empower businesses with innovative technology solutions.',
      visionStatement: 'To be the global leader in enterprise software.',
      coreValues: ['Innovation', 'Integrity', 'Customer Focus', 'Excellence'],
      strategicObjectives: ['Achieve ISO 27001 certification', 'Expand to APAC market', 'Launch AI-powered features', 'Improve customer NPS to 70+'],
      businessModel: 'B2B SaaS with enterprise licensing options',
      valueProposition: 'Secure, scalable enterprise software that reduces operational costs by 30%',
      ismsScope: 'The ISMS covers all information assets, systems, and processes related to the development, delivery, and support of enterprise software solutions across all locations.',
      ismsPolicy: 'Acme Corporation is committed to protecting the confidentiality, integrity, and availability of all information assets.',
      ismsObjectives: ['Maintain zero critical security incidents', 'Achieve 99.9% system availability', 'Complete annual security awareness training for all staff', 'Conduct quarterly vulnerability assessments'],
      departmentsInScope: ['Information Technology', 'Information Security', 'Product Development', 'Customer Support'],
      locationsInScope: ['Headquarters', 'European Office', 'Asia Pacific Office'],
      scopeExclusions: 'Physical manufacturing facilities and retail operations',
      exclusionJustification: 'No manufacturing or retail operations exist within the organization',
      isoCertificationStatus: 'in_progress',
      certificationBody: 'BSI Group',
      certificateNumber: null,
      certificationDate: null,
      certificationExpiry: null,
      nextAuditDate: new Date('2025-03-15'),
      riskAppetite: 'Moderate risk appetite with low tolerance for security and compliance risks.',
      digitalTransformationStage: 'managed',
      technologyAdoptionRate: 75,
      innovationFocus: ['Artificial Intelligence', 'Cloud Computing', 'Automation', 'Data Analytics'],
      esgRating: 'A-',
      sustainabilityGoals: ['Carbon neutral by 2030', 'Zero waste to landfill', '100% renewable energy'],
      createdById: users[0].id,
    },
  });
  console.log('✅ Created organisation profile');

  // Create Locations
  const locations = await Promise.all([
    prisma.location.create({
      data: {
        name: 'Headquarters',
        locationCode: 'LOC-HQ',
        locationType: 'headquarters',
        address: '123 Tech Park',
        city: 'San Francisco',
        state: 'California',
        country: 'United States',
        postalCode: '94025',
        region: 'North America',
        timezone: 'America/Los_Angeles',
        contactEmail: 'hq@acme.com',
        contactPhone: '+1 (555) 123-4567',
        employeeCount: 150,
        maxCapacity: 200,
        floorSpace: 15000,
        floorSpaceUnit: 'sqft',
        physicalSecurityLevel: 'high',
        accessControlType: 'biometric',
        securityFeatures: ['24/7 Security', 'CCTV', 'Access Cards', 'Visitor Management', 'Alarm System'],
        isDataCenter: false,
        hasServerRoom: true,
        networkType: 'fiber',
        internetProvider: 'AT&T Business',
        backupPower: true,
        inIsmsScope: true,
        scopeJustification: 'Primary business operations and development center',
        complianceCertifications: ['SOC 2 Type II', 'ISO 27001'],
        operationalSince: new Date('2015-06-01'),
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.location.create({
      data: {
        name: 'European Office',
        locationCode: 'LOC-EU',
        locationType: 'branch_office',
        address: '45 Innovation Street',
        city: 'London',
        state: 'Greater London',
        country: 'United Kingdom',
        postalCode: 'EC2A 4BX',
        region: 'EMEA',
        timezone: 'Europe/London',
        contactEmail: 'eu@acme.com',
        contactPhone: '+44 20 7123 4567',
        employeeCount: 60,
        maxCapacity: 80,
        floorSpace: 5000,
        floorSpaceUnit: 'sqft',
        physicalSecurityLevel: 'high',
        accessControlType: 'card_access',
        securityFeatures: ['CCTV', 'Access Cards', 'Reception Security', 'Alarm System'],
        isDataCenter: false,
        hasServerRoom: false,
        networkType: 'fiber',
        internetProvider: 'BT Business',
        backupPower: false,
        inIsmsScope: true,
        scopeJustification: 'European sales and support operations',
        complianceCertifications: ['ISO 27001'],
        operationalSince: new Date('2018-03-01'),
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.location.create({
      data: {
        name: 'Asia Pacific Office',
        locationCode: 'LOC-APAC',
        locationType: 'branch_office',
        address: '88 Marina Bay',
        city: 'Singapore',
        country: 'Singapore',
        postalCode: '018984',
        region: 'APAC',
        timezone: 'Asia/Singapore',
        contactEmail: 'apac@acme.com',
        contactPhone: '+65 6123 4567',
        employeeCount: 40,
        maxCapacity: 60,
        floorSpace: 3500,
        floorSpaceUnit: 'sqft',
        physicalSecurityLevel: 'medium',
        accessControlType: 'card_access',
        securityFeatures: ['CCTV', 'Access Cards', 'Building Security'],
        isDataCenter: false,
        hasServerRoom: false,
        networkType: 'fiber',
        internetProvider: 'Singtel',
        backupPower: false,
        inIsmsScope: true,
        scopeJustification: 'APAC regional operations',
        operationalSince: new Date('2021-01-15'),
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${locations.length} locations`);

  // Create Departments
  const departments = await Promise.all([
    prisma.department.create({
      data: {
        name: 'Executive Office',
        departmentCode: 'EXEC',
        description: 'Executive leadership and strategic management',
        departmentCategory: 'management',
        functionType: 'management',
        criticalityLevel: 'critical',
        headcount: 5,
        contractorCount: 0,
        budget: 2000000,
        budgetCurrency: 'USD',
        costCenter: 'CC-1000',
        keyResponsibilities: ['Strategic planning', 'Corporate governance', 'Stakeholder management', 'M&A decisions'],
        regulatoryObligations: ['SEC filings', 'Board reporting', 'Shareholder communications'],
        externalInterfaces: ['Board of Directors', 'Investors', 'Regulators'],
        location: 'Headquarters - Floor 10',
        floorPlanReference: 'HQ-F10',
        businessHours: { weekdays: '08:00-18:00', weekends: 'On-call' },
        contactEmail: 'executive@acme.com',
        contactPhone: '+1 (555) 123-4500',
        emergencyContact: { name: 'John Smith', phone: '+1 (555) 123-4501', email: 'john.smith@acme.com' },
        establishedDate: new Date('2015-01-01'),
        handlesPersonalData: true,
        handlesFinancialData: true,
        isActive: true,
        departmentHeadId: users[1].id,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Information Technology',
        departmentCode: 'IT',
        description: 'IT infrastructure, development, and support',
        departmentCategory: 'support_function',
        functionType: 'support',
        criticalityLevel: 'critical',
        headcount: 45,
        contractorCount: 8,
        budget: 5000000,
        budgetCurrency: 'USD',
        costCenter: 'CC-2000',
        keyResponsibilities: ['Infrastructure management', 'Application development', 'IT support', 'System administration', 'Network management'],
        regulatoryObligations: ['Data retention', 'System logging', 'Access control compliance'],
        externalInterfaces: ['Cloud providers', 'Software vendors', 'MSPs'],
        location: 'Headquarters - Floor 3-4',
        floorPlanReference: 'HQ-F3-F4',
        businessHours: { weekdays: '24/7', weekends: '24/7' },
        contactEmail: 'it@acme.com',
        contactPhone: '+1 (555) 123-4520',
        emergencyContact: { name: 'IT On-Call', phone: '+1 (555) 123-4599', email: 'it-oncall@acme.com' },
        establishedDate: new Date('2015-01-01'),
        handlesPersonalData: true,
        handlesFinancialData: false,
        isActive: true,
        departmentHeadId: users[2].id,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Information Security',
        departmentCode: 'INFOSEC',
        description: 'Cybersecurity, risk management, and compliance',
        departmentCategory: 'compliance_regulatory',
        functionType: 'support',
        criticalityLevel: 'critical',
        headcount: 12,
        contractorCount: 2,
        budget: 1500000,
        budgetCurrency: 'USD',
        costCenter: 'CC-2100',
        keyResponsibilities: ['Security operations', 'Risk management', 'Compliance monitoring', 'Incident response', 'Security awareness'],
        regulatoryObligations: ['ISO 27001', 'SOC 2', 'GDPR', 'Breach notification'],
        externalInterfaces: ['Auditors', 'Regulators', 'Security vendors', 'Penetration testers'],
        location: 'Headquarters - Floor 4',
        floorPlanReference: 'HQ-F4-SEC',
        businessHours: { weekdays: '24/7', weekends: '24/7' },
        contactEmail: 'security@acme.com',
        contactPhone: '+1 (555) 123-4530',
        emergencyContact: { name: 'Security On-Call', phone: '+1 (555) 123-4531', email: 'security-oncall@acme.com' },
        establishedDate: new Date('2018-06-01'),
        handlesPersonalData: true,
        handlesFinancialData: false,
        isActive: true,
        departmentHeadId: users[3].id,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Human Resources',
        departmentCode: 'HR',
        description: 'People management, recruitment, and employee relations',
        departmentCategory: 'support_function',
        functionType: 'support',
        criticalityLevel: 'medium',
        headcount: 15,
        contractorCount: 3,
        budget: 800000,
        budgetCurrency: 'USD',
        costCenter: 'CC-3000',
        keyResponsibilities: ['Recruitment', 'Onboarding', 'Performance management', 'Benefits administration', 'Training & development'],
        regulatoryObligations: ['Employment law compliance', 'Equal opportunity', 'Background checks', 'Data protection'],
        externalInterfaces: ['Recruitment agencies', 'Benefits providers', 'Training vendors'],
        location: 'Headquarters - Floor 2',
        floorPlanReference: 'HQ-F2',
        businessHours: { weekdays: '09:00-17:00', weekends: 'Closed' },
        contactEmail: 'hr@acme.com',
        contactPhone: '+1 (555) 123-4540',
        emergencyContact: { name: 'Emma Brown', phone: '+1 (555) 123-4541', email: 'emma.brown@acme.com' },
        establishedDate: new Date('2015-01-01'),
        handlesPersonalData: true,
        handlesFinancialData: true,
        isActive: true,
        departmentHeadId: users[4].id,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Sales & Marketing',
        departmentCode: 'SALES',
        description: 'Revenue generation and market development',
        departmentCategory: 'revenue_generating',
        functionType: 'core_business',
        criticalityLevel: 'high',
        headcount: 60,
        contractorCount: 5,
        budget: 3000000,
        budgetCurrency: 'USD',
        costCenter: 'CC-4000',
        keyResponsibilities: ['Lead generation', 'Sales pipeline management', 'Marketing campaigns', 'Customer acquisition', 'Brand management'],
        regulatoryObligations: ['Marketing consent', 'CAN-SPAM compliance', 'GDPR marketing'],
        externalInterfaces: ['Customers', 'Partners', 'Marketing agencies', 'Event organizers'],
        location: 'Headquarters - Floor 5-6',
        floorPlanReference: 'HQ-F5-F6',
        businessHours: { weekdays: '08:00-19:00', weekends: 'On-call' },
        contactEmail: 'sales@acme.com',
        contactPhone: '+1 (555) 123-4550',
        establishedDate: new Date('2015-03-01'),
        handlesPersonalData: true,
        handlesFinancialData: false,
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Product Development',
        departmentCode: 'PROD',
        description: 'Software product design and development',
        departmentCategory: 'revenue_generating',
        functionType: 'core_business',
        criticalityLevel: 'critical',
        headcount: 80,
        contractorCount: 15,
        budget: 8000000,
        budgetCurrency: 'USD',
        costCenter: 'CC-5000',
        keyResponsibilities: ['Product roadmap', 'Software development', 'Quality assurance', 'Release management', 'Technical documentation'],
        regulatoryObligations: ['Secure SDLC', 'Code review requirements', 'Accessibility compliance'],
        externalInterfaces: ['Open source communities', 'Technology partners', 'Beta customers'],
        location: 'Headquarters - Floor 7-9',
        floorPlanReference: 'HQ-F7-F9',
        businessHours: { weekdays: '09:00-18:00', weekends: 'Flexible' },
        contactEmail: 'product@acme.com',
        contactPhone: '+1 (555) 123-4560',
        establishedDate: new Date('2015-01-01'),
        handlesPersonalData: false,
        handlesFinancialData: false,
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Finance',
        departmentCode: 'FIN',
        description: 'Financial management and accounting',
        departmentCategory: 'support_function',
        functionType: 'support',
        criticalityLevel: 'high',
        headcount: 20,
        contractorCount: 2,
        budget: 1200000,
        budgetCurrency: 'USD',
        costCenter: 'CC-6000',
        keyResponsibilities: ['Financial reporting', 'Budgeting', 'Accounts payable/receivable', 'Tax compliance', 'Treasury management'],
        regulatoryObligations: ['GAAP compliance', 'Tax filings', 'Audit requirements', 'SOX controls'],
        externalInterfaces: ['External auditors', 'Banks', 'Tax authorities', 'Investors'],
        location: 'Headquarters - Floor 2',
        floorPlanReference: 'HQ-F2-FIN',
        businessHours: { weekdays: '08:00-18:00', weekends: 'Month-end' },
        contactEmail: 'finance@acme.com',
        contactPhone: '+1 (555) 123-4570',
        establishedDate: new Date('2015-01-01'),
        handlesPersonalData: true,
        handlesFinancialData: true,
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.department.create({
      data: {
        name: 'Legal & Compliance',
        departmentCode: 'LEGAL',
        description: 'Legal affairs and regulatory compliance',
        departmentCategory: 'compliance_regulatory',
        functionType: 'support',
        criticalityLevel: 'high',
        headcount: 8,
        contractorCount: 0,
        budget: 600000,
        budgetCurrency: 'USD',
        costCenter: 'CC-7000',
        keyResponsibilities: ['Contract management', 'Legal advisory', 'Regulatory compliance', 'IP protection', 'Litigation management'],
        regulatoryObligations: ['Corporate filings', 'Contract compliance', 'Regulatory reporting'],
        externalInterfaces: ['External counsel', 'Regulators', 'Courts', 'IP offices'],
        location: 'Headquarters - Floor 10',
        floorPlanReference: 'HQ-F10-LEGAL',
        businessHours: { weekdays: '09:00-18:00', weekends: 'On-call' },
        contactEmail: 'legal@acme.com',
        contactPhone: '+1 (555) 123-4580',
        establishedDate: new Date('2016-01-01'),
        handlesPersonalData: true,
        handlesFinancialData: false,
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${departments.length} departments`);

  // Create Business Processes
  const processes = await Promise.all([
    prisma.businessProcess.create({
      data: {
        name: 'Software Development Lifecycle',
        processCode: 'PROC-001',
        description: 'End-to-end software development from requirements to deployment',
        processType: 'core',
        criticalityLevel: 'critical',
        departmentId: departments[5].id,
        processOwnerId: users[2].id,
        backupOwnerId: users[3].id,
        frequency: 'continuous',
        automationLevel: 'semi_automated',
        cycleTimeHours: 336,
        inputs: ['Requirements documents', 'Design specifications', 'User stories', 'Bug reports'],
        outputs: ['Deployed software', 'Release notes', 'Technical documentation', 'Test reports'],
        keyActivities: ['Requirements analysis', 'Design', 'Development', 'Code review', 'Testing', 'Deployment'],
        stakeholders: ['Product Management', 'Engineering', 'QA', 'DevOps', 'Customer Success'],
        systemDependencies: ['GitHub', 'Jenkins', 'AWS', 'Jira', 'Confluence'],
        supplierDependencies: ['AWS', 'GitHub'],
        criticalRoles: ['Tech Lead', 'Senior Developer', 'DevOps Engineer'],
        requiredSkills: ['Software Development', 'Code Review', 'CI/CD', 'Testing'],
        riskRating: 'high',
        complianceRequirements: ['Secure SDLC', 'Code Review Policy', 'Change Management'],
        sopReference: 'SOP-DEV-001',
        lastReviewDate: new Date('2024-06-01'),
        nextReviewDate: new Date('2025-06-01'),
        improvementOpportunities: 'Implement automated security scanning in CI/CD pipeline',
        bcpEnabled: true,
        bcpCriticality: 'critical',
        recoveryTimeObjectiveMinutes: 240,
        recoveryPointObjectiveMinutes: 60,
        maximumTolerableDowntimeMinutes: 480,
        workRecoveryTimeMinutes: 120,
        minimumStaff: 5,
        recoveryStrategies: ['Failover to DR environment', 'Manual deployment procedures'],
        alternateProcesses: 'Manual code deployment via secure shell access',
        workaroundProcedures: 'Use backup CI/CD server or manual deployment',
        manualProcedures: 'SSH to production servers and deploy using deployment scripts',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.businessProcess.create({
      data: {
        name: 'Customer Onboarding',
        processCode: 'PROC-002',
        description: 'New customer setup and initial configuration',
        processType: 'core',
        criticalityLevel: 'high',
        departmentId: departments[4].id,
        frequency: 'daily',
        automationLevel: 'semi_automated',
        cycleTimeHours: 24,
        inputs: ['Signed contract', 'Customer requirements', 'Technical specifications'],
        outputs: ['Configured tenant', 'User accounts', 'Training materials', 'Welcome package'],
        keyActivities: ['Contract verification', 'Tenant provisioning', 'User setup', 'Initial training', 'Handover to support'],
        stakeholders: ['Sales', 'Customer Success', 'Technical Support', 'Finance'],
        systemDependencies: ['Salesforce', 'Product Platform', 'Email System'],
        criticalRoles: ['Customer Success Manager', 'Technical Onboarding Specialist'],
        requiredSkills: ['Customer communication', 'Technical configuration', 'Training delivery'],
        riskRating: 'medium',
        complianceRequirements: ['Data protection consent', 'Contract verification'],
        sopReference: 'SOP-SALES-002',
        lastReviewDate: new Date('2024-03-01'),
        nextReviewDate: new Date('2025-03-01'),
        bcpEnabled: true,
        bcpCriticality: 'high',
        recoveryTimeObjectiveMinutes: 480,
        recoveryPointObjectiveMinutes: 240,
        minimumStaff: 2,
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.businessProcess.create({
      data: {
        name: 'Incident Management',
        processCode: 'PROC-003',
        description: 'Security incident detection, response, and recovery',
        processType: 'support',
        criticalityLevel: 'critical',
        departmentId: departments[2].id,
        processOwnerId: users[3].id,
        frequency: 'continuous',
        automationLevel: 'semi_automated',
        cycleTimeHours: 4,
        inputs: ['Security alerts', 'User reports', 'Threat intelligence', 'Log data'],
        outputs: ['Incident reports', 'Remediation actions', 'Lessons learned', 'Updated controls'],
        keyActivities: ['Detection', 'Triage', 'Investigation', 'Containment', 'Eradication', 'Recovery', 'Post-incident review'],
        stakeholders: ['Security Team', 'IT Operations', 'Legal', 'Communications', 'Executive Team'],
        systemDependencies: ['SIEM', 'Ticketing System', 'EDR', 'Firewall'],
        criticalRoles: ['Incident Commander', 'Security Analyst', 'Forensic Investigator'],
        requiredSkills: ['Incident response', 'Forensics', 'Malware analysis', 'Communication'],
        riskRating: 'critical',
        complianceRequirements: ['Breach notification', 'Evidence preservation', 'Regulatory reporting'],
        sopReference: 'SOP-SEC-001',
        lastReviewDate: new Date('2024-09-01'),
        nextReviewDate: new Date('2025-03-01'),
        bcpEnabled: true,
        bcpCriticality: 'critical',
        recoveryTimeObjectiveMinutes: 30,
        recoveryPointObjectiveMinutes: 15,
        maximumTolerableDowntimeMinutes: 60,
        minimumStaff: 2,
        recoveryStrategies: ['Activate backup SOC', 'Engage MSSP'],
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.businessProcess.create({
      data: {
        name: 'Payroll Processing',
        processCode: 'PROC-004',
        description: 'Monthly payroll calculation and disbursement',
        processType: 'support',
        criticalityLevel: 'high',
        departmentId: departments[3].id,
        processOwnerId: users[4].id,
        frequency: 'monthly',
        automationLevel: 'fully_automated',
        cycleTimeHours: 48,
        inputs: ['Timesheets', 'Leave records', 'Expense claims', 'Tax information'],
        outputs: ['Payslips', 'Bank transfers', 'Tax reports', 'Pension contributions'],
        keyActivities: ['Data collection', 'Calculation', 'Approval', 'Payment processing', 'Reporting'],
        stakeholders: ['HR', 'Finance', 'All Employees', 'Tax Authorities'],
        systemDependencies: ['HRIS', 'Payroll System', 'Banking Portal'],
        supplierDependencies: ['Payroll Provider', 'Bank'],
        criticalRoles: ['Payroll Administrator', 'HR Manager', 'Finance Approver'],
        requiredSkills: ['Payroll processing', 'Tax compliance', 'Data accuracy'],
        riskRating: 'high',
        complianceRequirements: ['Tax compliance', 'Labor law', 'Data protection'],
        sopReference: 'SOP-HR-003',
        lastReviewDate: new Date('2024-01-01'),
        nextReviewDate: new Date('2025-01-01'),
        bcpEnabled: true,
        bcpCriticality: 'high',
        recoveryTimeObjectiveMinutes: 1440,
        recoveryPointObjectiveMinutes: 60,
        minimumStaff: 1,
        workaroundProcedures: 'Manual payroll calculation using spreadsheets',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.businessProcess.create({
      data: {
        name: 'Vendor Management',
        processCode: 'PROC-005',
        description: 'Third-party vendor assessment and relationship management',
        processType: 'support',
        criticalityLevel: 'medium',
        departmentId: departments[2].id,
        frequency: 'quarterly',
        automationLevel: 'manual',
        cycleTimeHours: 168,
        inputs: ['Vendor questionnaires', 'Security assessments', 'Contract terms', 'Performance data'],
        outputs: ['Vendor risk ratings', 'Approved vendor list', 'Contract renewals', 'Audit reports'],
        keyActivities: ['Vendor identification', 'Due diligence', 'Risk assessment', 'Contract negotiation', 'Ongoing monitoring'],
        stakeholders: ['Procurement', 'Security', 'Legal', 'Business Units'],
        systemDependencies: ['Vendor Management Platform', 'Contract Repository'],
        criticalRoles: ['Vendor Manager', 'Security Analyst'],
        requiredSkills: ['Vendor assessment', 'Contract review', 'Risk analysis'],
        riskRating: 'medium',
        complianceRequirements: ['Third-party risk management', 'Data processing agreements'],
        sopReference: 'SOP-SEC-005',
        lastReviewDate: new Date('2024-04-01'),
        nextReviewDate: new Date('2025-04-01'),
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${processes.length} business processes`);

  // Create External Dependencies
  const dependencies = await Promise.all([
    prisma.externalDependency.create({
      data: {
        name: 'Amazon Web Services',
        dependencyType: 'cloud_service_provider',
        description: 'Primary cloud infrastructure provider for all production workloads',
        criticalityLevel: 'critical',
        businessImpact: 'Complete service outage if unavailable',
        singlePointOfFailure: false,
        vendorWebsite: 'https://aws.amazon.com',
        primaryContact: 'AWS Enterprise Support',
        contactEmail: 'enterprise@aws.amazon.com',
        contactPhone: '+1 (800) 123-4567',
        contractReference: 'AWS-ENT-2023-001',
        contractStart: new Date('2023-01-01'),
        contractEnd: new Date('2026-01-01'),
        annualCost: 500000,
        paymentTerms: 'Monthly invoicing, Net 30',
        slaDetails: { availability: '99.99%', responseTime: '15 minutes', resolutionTime: '4 hours', penalties: 'Service credits' },
        dataProcessed: ['Customer data', 'Application logs', 'Backups', 'Analytics data'],
        dataLocation: 'US-East, EU-West',
        complianceCertifications: ['SOC 2 Type II', 'ISO 27001', 'PCI DSS', 'HIPAA', 'FedRAMP'],
        alternativeProviders: ['Microsoft Azure', 'Google Cloud Platform'],
        exitStrategy: 'Multi-cloud architecture allows migration to Azure within 30 days',
        dataRecoveryProcedure: 'S3 cross-region replication with automated failover',
        lastAssessmentDate: new Date('2024-06-01'),
        riskRating: 'low',
        createdById: users[0].id,
      },
    }),
    prisma.externalDependency.create({
      data: {
        name: 'Salesforce',
        dependencyType: 'saas_application',
        description: 'Customer relationship management platform',
        criticalityLevel: 'high',
        businessImpact: 'Sales operations impacted',
        singlePointOfFailure: false,
        vendorWebsite: 'https://www.salesforce.com',
        primaryContact: 'Salesforce Account Manager',
        contactEmail: 'support@salesforce.com',
        contactPhone: '+1 (800) 667-6389',
        contractReference: 'SF-2023-0456',
        contractStart: new Date('2023-06-01'),
        contractEnd: new Date('2025-06-01'),
        annualCost: 120000,
        paymentTerms: 'Annual prepaid',
        slaDetails: { availability: '99.9%', responseTime: '1 hour', resolutionTime: '24 hours' },
        dataProcessed: ['Customer contacts', 'Sales opportunities', 'Account data'],
        dataLocation: 'US (Primary), EU (Backup)',
        complianceCertifications: ['SOC 2 Type II', 'ISO 27001', 'GDPR compliant'],
        alternativeProviders: ['HubSpot', 'Microsoft Dynamics'],
        lastAssessmentDate: new Date('2024-03-01'),
        riskRating: 'low',
        createdById: users[0].id,
      },
    }),
    prisma.externalDependency.create({
      data: {
        name: 'Stripe',
        dependencyType: 'data_processor',
        description: 'Payment processing and billing',
        criticalityLevel: 'critical',
        businessImpact: 'Cannot process customer payments',
        singlePointOfFailure: true,
        vendorWebsite: 'https://stripe.com',
        primaryContact: 'Stripe Enterprise Support',
        contactEmail: 'enterprise@stripe.com',
        contactPhone: '+1 (888) 926-2289',
        contractReference: 'STRIPE-ENT-2022-789',
        contractStart: new Date('2022-01-01'),
        contractEnd: new Date('2025-01-01'),
        annualCost: 50000,
        paymentTerms: 'Transaction-based + monthly platform fee',
        slaDetails: { availability: '99.99%', responseTime: '30 minutes', resolutionTime: '4 hours', penalties: 'Fee credits' },
        dataProcessed: ['Payment card data', 'Transaction records', 'Customer billing info'],
        dataLocation: 'US, EU',
        complianceCertifications: ['PCI DSS Level 1', 'SOC 2 Type II', 'ISO 27001'],
        alternativeProviders: ['Adyen', 'Braintree'],
        exitStrategy: 'Payment abstraction layer allows switch within 2 weeks',
        dataRecoveryProcedure: 'Transaction data exported via API, stored in internal systems',
        lastAssessmentDate: new Date('2024-09-01'),
        riskRating: 'medium',
        createdById: users[0].id,
      },
    }),
    prisma.externalDependency.create({
      data: {
        name: 'Okta',
        dependencyType: 'saas_application',
        description: 'Identity and access management',
        criticalityLevel: 'critical',
        businessImpact: 'Users cannot authenticate to systems',
        singlePointOfFailure: true,
        vendorWebsite: 'https://www.okta.com',
        primaryContact: 'Okta Customer Success',
        contactEmail: 'support@okta.com',
        contactPhone: '+1 (888) 722-7871',
        contractReference: 'OKTA-2023-1234',
        contractStart: new Date('2023-03-01'),
        contractEnd: new Date('2026-03-01'),
        annualCost: 80000,
        paymentTerms: 'Annual prepaid',
        slaDetails: { availability: '99.99%', responseTime: '15 minutes', resolutionTime: '2 hours' },
        dataProcessed: ['User identities', 'Authentication logs', 'Access policies'],
        dataLocation: 'US',
        complianceCertifications: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP'],
        alternativeProviders: ['Azure AD', 'Ping Identity', 'OneLogin'],
        exitStrategy: 'SCIM provisioning allows migration to alternative IdP',
        lastAssessmentDate: new Date('2024-08-01'),
        riskRating: 'low',
        createdById: users[0].id,
      },
    }),
    prisma.externalDependency.create({
      data: {
        name: 'Deloitte',
        dependencyType: 'professional_service',
        description: 'External audit and compliance consulting',
        criticalityLevel: 'medium',
        businessImpact: 'Audit delays',
        singlePointOfFailure: false,
        vendorWebsite: 'https://www.deloitte.com',
        primaryContact: 'Audit Partner',
        contactEmail: 'audit@deloitte.com',
        contactPhone: '+1 (212) 489-1600',
        contractReference: 'DEL-AUDIT-2024',
        contractStart: new Date('2024-01-01'),
        contractEnd: new Date('2025-01-01'),
        annualCost: 200000,
        paymentTerms: 'Milestone-based payments',
        dataProcessed: ['Financial records', 'Audit evidence', 'Control documentation'],
        dataLocation: 'US (Deloitte secure portal)',
        complianceCertifications: ['SOC 2 Type II'],
        alternativeProviders: ['PwC', 'EY', 'KPMG'],
        lastAssessmentDate: new Date('2024-01-15'),
        riskRating: 'low',
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${dependencies.length} external dependencies`);

  // Create Regulators
  const regulators = await Promise.all([
    prisma.regulator.create({
      data: {
        name: 'Information Commissioner\'s Office',
        acronym: 'ICO',
        regulatorType: 'data_protection_authority',
        jurisdiction: 'United Kingdom',
        jurisdictionLevel: 'national',
        description: 'UK data protection regulator responsible for enforcing GDPR and UK data protection laws',
        website: 'https://ico.org.uk',
        contactEmail: 'casework@ico.org.uk',
        contactPhone: '+44 303 123 1113',
        contactAddress: 'Wycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF',
        keyRegulations: ['UK GDPR', 'Data Protection Act 2018', 'PECR', 'Freedom of Information Act'],
        applicableStandards: ['ISO 27001', 'ISO 27701'],
        registrationStatus: 'registered',
        registrationNumber: 'ZA123456',
        registrationDate: new Date('2018-05-25'),
        renewalDate: new Date('2025-05-25'),
        reportingFrequency: 'annual',
        lastReportDate: new Date('2024-03-15'),
        nextReportDate: new Date('2025-03-15'),
        lastInspectionDate: null,
        nextInspectionDate: null,
        complianceNotes: 'Annual data protection fee paid. No outstanding enforcement actions.',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.regulator.create({
      data: {
        name: 'European Union Agency for Cybersecurity',
        acronym: 'ENISA',
        regulatorType: 'government_agency',
        jurisdiction: 'European Union',
        jurisdictionLevel: 'regional',
        description: 'EU cybersecurity agency providing guidance and coordination on cybersecurity matters',
        website: 'https://www.enisa.europa.eu',
        contactEmail: 'info@enisa.europa.eu',
        contactAddress: 'Vasilissis Sofias 1, Marousi 151 24, Athens, Greece',
        keyRegulations: ['NIS2 Directive', 'Cybersecurity Act', 'DORA'],
        applicableStandards: ['ISO 27001', 'NIST CSF', 'CIS Controls'],
        registrationStatus: 'not_required',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.regulator.create({
      data: {
        name: 'ISO/IEC',
        acronym: 'ISO',
        regulatorType: 'standards_organization',
        jurisdiction: 'International',
        jurisdictionLevel: 'international',
        description: 'International standards organization developing and publishing international standards',
        website: 'https://www.iso.org',
        contactEmail: 'central@iso.org',
        contactAddress: 'ISO Central Secretariat, Chemin de Blandonnet 8, 1214 Vernier, Geneva, Switzerland',
        keyRegulations: [],
        applicableStandards: ['ISO 27001', 'ISO 27002', 'ISO 27017', 'ISO 27018', 'ISO 27701', 'ISO 22301'],
        registrationStatus: 'not_required',
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${regulators.length} regulators`);

  // Create Security Committee
  const committee = await prisma.securityCommittee.create({
    data: {
      name: 'Information Security Steering Committee',
      committeeType: 'steering',
      description: 'Executive oversight of information security strategy and governance',
      chairId: users[1].id,
      authorityLevel: 'Strategic decision-making authority for security investments and policies',
      meetingFrequency: 'monthly',
      nextMeetingDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      isActive: true,
      establishedDate: new Date('2023-01-15'),
      createdById: users[0].id,
    },
  });
  console.log('✅ Created security committee');

  // Create Committee Memberships
  const memberships = await Promise.all([
    prisma.committeeMembership.create({
      data: {
        userId: users[1].id,
        committeeId: committee.id,
        role: 'chair',
        responsibilities: 'Chair meetings, set agenda, ensure decisions are implemented',
        votingRights: true,
        isActive: true,
        startDate: new Date('2023-01-15'),
        createdById: users[0].id,
      },
    }),
    prisma.committeeMembership.create({
      data: {
        userId: users[2].id,
        committeeId: committee.id,
        role: 'member',
        responsibilities: 'Provide IT perspective on security matters',
        votingRights: true,
        isActive: true,
        startDate: new Date('2023-01-15'),
        createdById: users[0].id,
      },
    }),
    prisma.committeeMembership.create({
      data: {
        userId: users[3].id,
        committeeId: committee.id,
        role: 'secretary',
        responsibilities: 'Present security reports, recommend policies, take minutes',
        votingRights: true,
        isActive: true,
        startDate: new Date('2023-01-15'),
        createdById: users[0].id,
      },
    }),
    prisma.committeeMembership.create({
      data: {
        userId: users[4].id,
        committeeId: committee.id,
        role: 'member',
        responsibilities: 'Provide HR perspective on security awareness and training',
        votingRights: true,
        isActive: true,
        startDate: new Date('2023-06-01'),
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${memberships.length} committee memberships`);

  // Create Committee Meeting
  const meeting = await prisma.committeeMeeting.create({
    data: {
      committeeId: committee.id,
      meetingNumber: '2024-Q4-01',
      title: 'Q4 Security Review Meeting',
      meetingType: 'regular',
      meetingDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      startTime: '10:00',
      endTime: '11:30',
      durationMinutes: 90,
      locationType: 'hybrid',
      physicalLocation: 'Board Room A',
      virtualMeetingLink: 'https://zoom.us/j/123456789',
      agenda: '1. Review Q3 security metrics\n2. Discuss upcoming audit\n3. Approve security budget\n4. AOB',
      objectives: 'Review security posture and approve Q1 initiatives',
      minutes: 'Meeting opened at 10:00. All members present. Q3 metrics reviewed - 15% reduction in incidents. Audit preparation on track. Budget approved unanimously.',
      chairId: users[1].id,
      secretaryId: users[3].id,
      expectedAttendeesCount: 4,
      actualAttendeesCount: 4,
      status: 'completed',
      quorumAchieved: true,
      quorumRequirement: 3,
      createdById: users[0].id,
    },
  });
  console.log('✅ Created committee meeting');

  // Create Meeting Decisions
  const decisions = await Promise.all([
    prisma.meetingDecision.create({
      data: {
        meetingId: meeting.id,
        decisionNumber: 'DEC-2024-001',
        title: 'Approve Q1 2025 Security Budget',
        description: 'Approved security budget of $1.5M for Q1 2025, including new SIEM implementation',
        decisionType: 'approved',
        rationale: 'Critical for improving threat detection capabilities',
        voteType: 'unanimous',
        votesFor: 4,
        votesAgainst: 0,
        votesAbstain: 0,
        responsiblePartyId: users[3].id,
        effectiveDate: new Date('2025-01-01'),
        implementationDeadline: new Date('2025-03-31'),
        implemented: false,
        createdById: users[0].id,
      },
    }),
    prisma.meetingDecision.create({
      data: {
        meetingId: meeting.id,
        decisionNumber: 'DEC-2024-002',
        title: 'Mandatory Security Awareness Training',
        description: 'All employees must complete updated security awareness training by end of Q1',
        decisionType: 'approved',
        rationale: 'Reduce human-factor security incidents',
        voteType: 'majority',
        votesFor: 4,
        votesAgainst: 0,
        votesAbstain: 0,
        responsiblePartyId: users[4].id,
        effectiveDate: new Date('2025-01-01'),
        implementationDeadline: new Date('2025-03-31'),
        implemented: false,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${decisions.length} meeting decisions`);

  // Create Meeting Action Items
  const actionItems = await Promise.all([
    prisma.meetingActionItem.create({
      data: {
        meetingId: meeting.id,
        actionNumber: 'ACT-2024-001',
        title: 'Prepare SIEM vendor shortlist',
        description: 'Research and prepare a shortlist of 3 SIEM vendors for evaluation',
        assignedToId: users[3].id,
        assignedById: users[1].id,
        priority: 'high',
        dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
        status: 'in_progress',
        progressPercentage: 60,
        createdById: users[0].id,
      },
    }),
    prisma.meetingActionItem.create({
      data: {
        meetingId: meeting.id,
        actionNumber: 'ACT-2024-002',
        title: 'Update security awareness training content',
        description: 'Review and update training materials to include latest phishing techniques',
        assignedToId: users[4].id,
        assignedById: users[1].id,
        priority: 'medium',
        dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        status: 'open',
        progressPercentage: 0,
        createdById: users[0].id,
      },
    }),
    prisma.meetingActionItem.create({
      data: {
        meetingId: meeting.id,
        actionNumber: 'ACT-2024-003',
        title: 'Schedule external penetration test',
        description: 'Coordinate with vendor to schedule annual penetration test for Q1',
        assignedToId: users[3].id,
        assignedById: users[1].id,
        priority: 'high',
        dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // Overdue
        status: 'open',
        progressPercentage: 20,
        createdById: users[0].id,
      },
    }),
    prisma.meetingActionItem.create({
      data: {
        meetingId: meeting.id,
        actionNumber: 'ACT-2024-004',
        title: 'Review access control policies',
        description: 'Annual review of access control policies and procedures',
        assignedToId: users[2].id,
        assignedById: users[3].id,
        priority: 'medium',
        dueDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        status: 'open',
        progressPercentage: 0,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${actionItems.length} action items`);

  // Create Executive Positions
  const executives = await Promise.all([
    prisma.executivePosition.create({
      data: {
        title: 'Chief Executive Officer',
        executiveLevel: 'ceo',
        personId: users[1].id,
        authorityLevel: 'strategic',
        securityResponsibilities: 'Ultimate accountability for information security',
        budgetAuthority: true,
        isActive: true,
        isCeo: true,
        isSecurityCommitteeMember: true,
        startDate: new Date('2020-01-01'),
        createdById: users[0].id,
      },
    }),
    prisma.executivePosition.create({
      data: {
        title: 'Chief Information Security Officer',
        executiveLevel: 'ciso',
        personId: users[3].id,
        authorityLevel: 'strategic',
        securityResponsibilities: 'Lead information security program, risk management, and compliance',
        budgetAuthority: true,
        isActive: true,
        isSecurityCommitteeMember: true,
        startDate: new Date('2022-03-01'),
        createdById: users[0].id,
      },
    }),
    prisma.executivePosition.create({
      data: {
        title: 'Chief Technology Officer',
        executiveLevel: 'cto',
        personId: users[2].id,
        authorityLevel: 'strategic',
        securityResponsibilities: 'Ensure security is embedded in technology decisions',
        budgetAuthority: true,
        isActive: true,
        isSecurityCommitteeMember: true,
        startDate: new Date('2021-06-01'),
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${executives.length} executive positions`);

  // Create Security Champions
  const champions = await Promise.all([
    prisma.securityChampion.create({
      data: {
        userId: users[2].id,
        departmentId: departments[1].id,
        championLevel: 'primary',
        responsibilities: 'Promote security best practices within IT department',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-06-15'),
        isActive: true,
        startDate: new Date('2023-03-01'),
        createdById: users[0].id,
      },
    }),
    prisma.securityChampion.create({
      data: {
        userId: users[4].id,
        departmentId: departments[3].id,
        championLevel: 'primary',
        responsibilities: 'Security awareness liaison for HR department',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-06-15'),
        isActive: true,
        startDate: new Date('2023-06-01'),
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${champions.length} security champions`);

  // Create Survey Questions for DORA
  const doraQuestions = [
    { stepNumber: '1.1', stepCategory: 'JURISDICTION', questionText: 'Is your organization established in an EU/EEA Member State?', ifYes: 'Continue to Step 2', ifNo: 'STOP: DORA does not apply', legalReference: 'Art. 2(1)', sortOrder: 1 },
    { stepNumber: '2.1', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization a credit institution?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.2', legalReference: 'Art. 2(1)(a)', sortOrder: 2 },
    { stepNumber: '2.2', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization a payment institution?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.3', legalReference: 'Art. 2(1)(b)', sortOrder: 3 },
    { stepNumber: '2.3', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization an investment firm?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.4', legalReference: 'Art. 2(1)(c)', sortOrder: 4 },
    { stepNumber: '2.4', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization an insurance or reinsurance undertaking?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.5', legalReference: 'Art. 2(1)(d)', sortOrder: 5 },
    { stepNumber: '2.5', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization an electronic money institution?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.6', legalReference: 'Art. 2(1)(e)', sortOrder: 6 },
    { stepNumber: '2.6', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization a crypto-asset service provider?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.7', legalReference: 'Art. 2(1)(f)', sortOrder: 7 },
    { stepNumber: '2.7', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization a central securities depository?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.8', legalReference: 'Art. 2(1)(g)', sortOrder: 8 },
    { stepNumber: '2.8', stepCategory: 'ENTITY TYPE', questionText: 'Is your organization a trading venue?', ifYes: 'DORA applies - Full regime', ifNo: 'Continue to 2.9', legalReference: 'Art. 2(1)(h)', sortOrder: 9 },
    { stepNumber: '2.9', stepCategory: 'ICT THIRD-PARTY', questionText: 'Are you an ICT Third-Party Service Provider to any of the above entities?', ifYes: 'DORA applies (Third-party provisions)', ifNo: 'STOP: DORA likely does NOT apply', legalReference: 'Art. 2(1)(u), Art. 31-44', sortOrder: 10 },
    { stepNumber: '3.1', stepCategory: 'EXEMPTION CHECK', questionText: '[If AIFM] Do you manage portfolios with AUM below €100M (leveraged) or €500M (unleveraged)?', ifYes: 'EXEMPT: Small AIFM exemption', ifNo: 'DORA applies - Skip to Step 5', legalReference: 'Art. 2(3)(a)', sortOrder: 11 },
    { stepNumber: '3.2', stepCategory: 'EXEMPTION CHECK', questionText: '[If Insurance] Are you exempt under Solvency II Directive Art. 4?', ifYes: 'EXEMPT: Small insurer exemption', ifNo: 'DORA applies - Skip to Step 5', legalReference: 'Art. 2(3)(b)', sortOrder: 12 },
    { stepNumber: '4.1', stepCategory: 'SIZE CHECK', questionText: '[If Insurance Intermediary] Do you employ fewer than 10 persons?', ifYes: 'Continue to 4.2', ifNo: 'Continue to 4.3', legalReference: 'Art. 2(3)(e)', sortOrder: 13 },
    { stepNumber: '4.2', stepCategory: 'SIZE CHECK', questionText: 'Is your annual turnover AND balance sheet each below €2 million?', ifYes: 'EXEMPT: Microenterprise exemption', ifNo: 'Continue to 4.3', legalReference: 'Art. 2(3)(e)', sortOrder: 14 },
    { stepNumber: '5.1', stepCategory: 'REGIME DETERMINATION', questionText: 'Are you a microenterprise (< 10 employees AND turnover/balance sheet < €2M)?', ifYes: 'Simplified ICT Risk Management Framework applies (Art. 16)', ifNo: 'Full DORA requirements apply', legalReference: 'Art. 16', sortOrder: 15 },
  ];

  const nis2Questions = [
    { stepNumber: '1.1', stepCategory: 'JURISDICTION', questionText: 'Does your organization provide services or carry out activities within the European Union?', ifYes: 'Continue to Step 2', ifNo: 'STOP: NIS2 does not apply', legalReference: 'Art. 2(1)', sortOrder: 1 },
    { stepNumber: '2.1', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization operate in the Energy sector?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.2', legalReference: 'Annex I', sortOrder: 2 },
    { stepNumber: '2.2', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization operate in the Transport sector?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.3', legalReference: 'Annex I', sortOrder: 3 },
    { stepNumber: '2.3', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization operate in the Banking sector?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.4', legalReference: 'Annex I', sortOrder: 4 },
    { stepNumber: '2.4', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization provide Digital infrastructure services?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.5', legalReference: 'Annex I', sortOrder: 5 },
    { stepNumber: '2.5', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization operate in the Health sector?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.6', legalReference: 'Annex I', sortOrder: 6 },
    { stepNumber: '2.6', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization provide Drinking water or Wastewater services?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.7', legalReference: 'Annex I', sortOrder: 7 },
    { stepNumber: '2.7', stepCategory: 'SECTOR - ANNEX I', questionText: 'Does your organization operate in the Space sector?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.8', legalReference: 'Annex I', sortOrder: 8 },
    { stepNumber: '2.8', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization provide Postal and courier services?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.9', legalReference: 'Annex II', sortOrder: 9 },
    { stepNumber: '2.9', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization operate in Waste management?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.10', legalReference: 'Annex II', sortOrder: 10 },
    { stepNumber: '2.10', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization manufacture, produce, or distribute chemicals?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.11', legalReference: 'Annex II', sortOrder: 11 },
    { stepNumber: '2.11', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization manufacture, produce, or distribute food?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.12', legalReference: 'Annex II', sortOrder: 12 },
    { stepNumber: '2.12', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization provide Digital services (online marketplace, search engine, social network)?', ifYes: 'Continue to size assessment', ifNo: 'Continue to 2.13', legalReference: 'Annex II', sortOrder: 13 },
    { stepNumber: '2.13', stepCategory: 'SECTOR - ANNEX II', questionText: 'Does your organization conduct Research activities?', ifYes: 'Continue to size assessment', ifNo: 'STOP: NIS2 likely does NOT apply', legalReference: 'Annex II', sortOrder: 14 },
    { stepNumber: '3.1', stepCategory: 'SIZE THRESHOLD', questionText: 'Does your organization have 250 or more employees?', ifYes: 'NIS2 applies - Continue to classification', ifNo: 'Continue to 3.2', legalReference: 'Art. 2(1)', sortOrder: 15 },
    { stepNumber: '3.2', stepCategory: 'SIZE THRESHOLD', questionText: 'Does your organization have annual turnover exceeding €50 million?', ifYes: 'NIS2 applies - Continue to classification', ifNo: 'Continue to 3.3', legalReference: 'Art. 2(1)', sortOrder: 16 },
    { stepNumber: '3.3', stepCategory: 'SIZE THRESHOLD', questionText: 'Does your organization have annual balance sheet exceeding €43 million?', ifYes: 'NIS2 applies - Continue to classification', ifNo: 'Continue to 3.4', legalReference: 'Art. 2(1)', sortOrder: 17 },
    { stepNumber: '3.4', stepCategory: 'SPECIAL CASES', questionText: 'Are you a qualified Trust Service Provider?', ifYes: 'NIS2 applies regardless of size', ifNo: 'Continue to 3.5', legalReference: 'Art. 2(2)(a)', sortOrder: 18 },
    { stepNumber: '3.5', stepCategory: 'SPECIAL CASES', questionText: 'Are you a TLD registry or DNS service provider?', ifYes: 'NIS2 applies regardless of size', ifNo: 'Continue to 3.6', legalReference: 'Art. 2(2)(b)', sortOrder: 19 },
    { stepNumber: '3.6', stepCategory: 'SPECIAL CASES', questionText: 'Are you a public electronic communications network or service provider?', ifYes: 'NIS2 applies regardless of size', ifNo: 'STOP: Below size threshold', legalReference: 'Art. 2(2)(c)', sortOrder: 20 },
    { stepNumber: '4.1', stepCategory: 'ENTITY CLASSIFICATION', questionText: 'Are you in an Annex I sector AND a large enterprise (≥250 employees OR turnover >€50M)?', ifYes: 'You are an ESSENTIAL entity', ifNo: 'Continue to 4.2', legalReference: 'Art. 3(1)(a)', sortOrder: 21 },
    { stepNumber: '4.2', stepCategory: 'ENTITY CLASSIFICATION', questionText: 'Have you been identified as critical entity under CER Directive?', ifYes: 'You are an ESSENTIAL entity', ifNo: 'You are an IMPORTANT entity', legalReference: 'Art. 3(1)(f)', sortOrder: 22 },
  ];

  await prisma.surveyQuestion.createMany({
    data: [
      ...doraQuestions.map(q => ({ ...q, surveyType: 'dora' })),
      ...nis2Questions.map(q => ({ ...q, surveyType: 'nis2' })),
    ],
    skipDuplicates: true,
  });
  console.log('✅ Created survey questions for DORA and NIS2');

  // Create Key Personnel
  const keyPersonnel = await Promise.all([
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-001',
        name: 'John Smith',
        jobTitle: 'Chief Executive Officer',
        email: 'john.smith@riskready.com',
        phone: '+1 555-0101',
        ismsRole: 'executive_sponsor',
        securityResponsibilities: 'Ultimate accountability for information security and ISMS effectiveness',
        authorityLevel: 'executive',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-06-01'),
        certifications: ['CISM'],
        isActive: true,
        startDate: new Date('2020-01-01'),
        userId: users[1].id,
        createdById: users[0].id,
      },
    }),
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-002',
        name: 'Mike Wilson',
        jobTitle: 'Chief Information Security Officer',
        email: 'mike.wilson@riskready.com',
        phone: '+1 555-0103',
        ismsRole: 'ciso',
        securityResponsibilities: 'Lead information security program, risk management, compliance, and ISMS management',
        authorityLevel: 'executive',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-09-15'),
        certifications: ['CISSP', 'CISM', 'ISO 27001 Lead Auditor'],
        isActive: true,
        startDate: new Date('2022-03-01'),
        userId: users[3].id,
        createdById: users[0].id,
      },
    }),
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-003',
        name: 'Sarah Jones',
        jobTitle: 'IT Director',
        email: 'sarah.jones@riskready.com',
        phone: '+1 555-0102',
        ismsRole: 'it_manager',
        securityResponsibilities: 'Ensure IT systems comply with security policies and standards',
        authorityLevel: 'management',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-08-01'),
        certifications: ['CISA'],
        isActive: true,
        startDate: new Date('2021-06-01'),
        userId: users[2].id,
        createdById: users[0].id,
      },
    }),
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-004',
        name: 'Emma Brown',
        jobTitle: 'HR Director',
        email: 'emma.brown@riskready.com',
        phone: '+1 555-0104',
        ismsRole: 'hr_manager',
        securityResponsibilities: 'Security awareness training, personnel security, and HR-related security controls',
        authorityLevel: 'management',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-07-15'),
        isActive: true,
        startDate: new Date('2022-01-01'),
        userId: users[4].id,
        createdById: users[0].id,
      },
    }),
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-005',
        name: 'David Chen',
        jobTitle: 'Data Protection Officer',
        email: 'david.chen@riskready.com',
        phone: '+1 555-0105',
        ismsRole: 'dpo',
        securityResponsibilities: 'GDPR compliance, data subject rights, privacy impact assessments',
        authorityLevel: 'management',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-10-01'),
        certifications: ['CIPP/E', 'CIPM'],
        isActive: true,
        startDate: new Date('2023-01-15'),
        createdById: users[0].id,
      },
    }),
    prisma.keyPersonnel.create({
      data: {
        personCode: 'KP-006',
        name: 'Lisa Martinez',
        jobTitle: 'Internal Auditor',
        email: 'lisa.martinez@riskready.com',
        phone: '+1 555-0106',
        ismsRole: 'internal_auditor',
        securityResponsibilities: 'ISMS internal audits, compliance verification, audit reporting',
        authorityLevel: 'operational',
        trainingCompleted: true,
        lastTrainingDate: new Date('2024-05-01'),
        certifications: ['ISO 27001 Lead Auditor', 'CIA'],
        isActive: true,
        startDate: new Date('2023-06-01'),
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${keyPersonnel.length} key personnel`);

  // Set backup relationships
  await prisma.keyPersonnel.update({
    where: { id: keyPersonnel[1].id },
    data: { backupPersonId: keyPersonnel[2].id },
  });
  await prisma.keyPersonnel.update({
    where: { id: keyPersonnel[4].id },
    data: { backupPersonId: keyPersonnel[1].id },
  });
  console.log('✅ Set key personnel backup relationships');

  // Create Applicable Frameworks
  const frameworks = await Promise.all([
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'ISO27001',
        name: 'ISO/IEC 27001:2022',
        frameworkType: 'standard',
        description: 'Information security management systems — Requirements',
        version: '2022',
        isApplicable: true,
        applicabilityReason: 'Core ISMS certification standard',
        applicabilityDate: new Date('2023-01-01'),
        complianceStatus: 'partially_compliant',
        compliancePercentage: 75,
        lastAssessmentDate: new Date('2024-09-01'),
        nextAssessmentDate: new Date('2025-03-01'),
        isCertifiable: true,
        certificationStatus: 'in_progress',
        keyRequirements: ['Risk Assessment', 'Statement of Applicability', 'Internal Audit', 'Management Review'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'GDPR',
        name: 'General Data Protection Regulation',
        frameworkType: 'regulation',
        description: 'EU regulation on data protection and privacy',
        version: '2016/679',
        isApplicable: true,
        applicabilityReason: 'Process personal data of EU residents',
        applicabilityDate: new Date('2023-01-01'),
        complianceStatus: 'compliant',
        compliancePercentage: 90,
        lastAssessmentDate: new Date('2024-06-01'),
        nextAssessmentDate: new Date('2025-06-01'),
        supervisoryAuthority: 'Information Commissioner\'s Office (ICO)',
        registrationNumber: 'ZA123456',
        isCertifiable: false,
        keyRequirements: ['Lawful Basis', 'Data Subject Rights', 'Breach Notification', 'DPO Appointment'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'SOC2',
        name: 'SOC 2 Type II',
        frameworkType: 'standard',
        description: 'Service Organization Control 2 - Trust Services Criteria',
        version: '2017',
        isApplicable: true,
        applicabilityReason: 'Customer requirement for SaaS services',
        applicabilityDate: new Date('2023-06-01'),
        complianceStatus: 'compliant',
        compliancePercentage: 95,
        lastAssessmentDate: new Date('2024-08-01'),
        nextAssessmentDate: new Date('2025-08-01'),
        isCertifiable: true,
        certificationStatus: 'certified',
        certificationBody: 'Deloitte',
        certificateNumber: 'SOC2-2024-001',
        certificationDate: new Date('2024-08-15'),
        certificationExpiry: new Date('2025-08-15'),
        keyRequirements: ['Security', 'Availability', 'Confidentiality', 'Processing Integrity', 'Privacy'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'DORA',
        name: 'Digital Operational Resilience Act',
        frameworkType: 'regulation',
        description: 'EU regulation on digital operational resilience for the financial sector',
        version: '2022/2554',
        isApplicable: false,
        applicabilityReason: 'Not a financial entity - DORA does not apply',
        applicabilityDate: new Date('2024-01-01'),
        complianceStatus: 'not_assessed',
        isCertifiable: false,
        keyRequirements: ['ICT Risk Management', 'Incident Reporting', 'Digital Resilience Testing', 'Third-Party Risk'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'NIS2',
        name: 'Network and Information Security Directive 2',
        frameworkType: 'directive',
        description: 'EU directive on cybersecurity for essential and important entities',
        version: '2022/2555',
        isApplicable: false,
        applicabilityReason: 'Below size threshold and not in covered sector',
        applicabilityDate: new Date('2024-01-01'),
        complianceStatus: 'not_assessed',
        isCertifiable: false,
        keyRequirements: ['Risk Management', 'Incident Handling', 'Business Continuity', 'Supply Chain Security'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'ISO27701',
        name: 'ISO/IEC 27701:2019',
        frameworkType: 'standard',
        description: 'Privacy Information Management System extension to ISO 27001',
        version: '2019',
        isApplicable: true,
        applicabilityReason: 'Extension to ISO 27001 for privacy management',
        applicabilityDate: new Date('2024-01-01'),
        complianceStatus: 'partially_compliant',
        compliancePercentage: 45,
        lastAssessmentDate: new Date('2024-06-01'),
        nextAssessmentDate: new Date('2025-06-01'),
        isCertifiable: true,
        certificationStatus: 'planned',
        keyRequirements: ['PII Controller Controls', 'PII Processor Controls', 'Privacy Risk Assessment'],
        createdById: users[0].id,
      },
    }),
    prisma.applicableFramework.create({
      data: {
        frameworkCode: 'NIST-CSF',
        name: 'NIST Cybersecurity Framework',
        frameworkType: 'framework',
        description: 'US framework for improving critical infrastructure cybersecurity',
        version: '2.0',
        isApplicable: true,
        applicabilityReason: 'Best practice framework for US operations',
        applicabilityDate: new Date('2024-01-01'),
        complianceStatus: 'partially_compliant',
        compliancePercentage: 60,
        lastAssessmentDate: new Date('2024-03-01'),
        nextAssessmentDate: new Date('2025-03-01'),
        isCertifiable: false,
        keyRequirements: ['Identify', 'Protect', 'Detect', 'Respond', 'Recover', 'Govern'],
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${frameworks.length} applicable frameworks`);

  // Create Context Issues (ISO 27001 Clause 4.1)
  const contextIssues = await Promise.all([
    prisma.contextIssue.create({
      data: {
        issueCode: 'CTX-INT-001',
        issueType: 'internal',
        category: 'organizational',
        title: 'Rapid Growth and Scaling Challenges',
        description: 'The organization is experiencing rapid growth which creates challenges in maintaining consistent security practices across new teams and locations.',
        impactType: 'operational',
        impactLevel: 'high',
        likelihood: 'high',
        ismsRelevance: 'Requires scalable security controls and processes that can adapt to organizational growth',
        affectedAreas: ['Information Security', 'IT Operations', 'HR', 'All Departments'],
        controlImplications: 'Need for automated security controls, standardized onboarding, and scalable access management',
        responseStrategy: 'Implement security automation and standardized processes',
        mitigationActions: ['Automate access provisioning', 'Standardize security training', 'Implement security-as-code'],
        monitoringFrequency: 'monthly',
        lastReviewDate: new Date('2024-09-01'),
        nextReviewDate: new Date('2025-03-01'),
        trendDirection: 'stable',
        status: 'active',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.contextIssue.create({
      data: {
        issueCode: 'CTX-INT-002',
        issueType: 'internal',
        category: 'technical',
        title: 'Legacy System Integration',
        description: 'Some legacy systems lack modern security features and require additional controls to meet current security standards.',
        impactType: 'security',
        impactLevel: 'medium',
        likelihood: 'medium',
        ismsRelevance: 'Legacy systems may not support modern authentication or encryption standards',
        affectedAreas: ['IT Operations', 'Product Development'],
        controlImplications: 'Compensating controls needed for legacy systems until modernization',
        responseStrategy: 'Phased modernization with compensating controls',
        mitigationActions: ['Network segmentation', 'Enhanced monitoring', 'Planned migration'],
        monitoringFrequency: 'quarterly',
        lastReviewDate: new Date('2024-06-01'),
        nextReviewDate: new Date('2025-06-01'),
        trendDirection: 'improving',
        status: 'active',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.contextIssue.create({
      data: {
        issueCode: 'CTX-EXT-001',
        issueType: 'external',
        category: 'regulatory',
        title: 'Evolving Data Protection Regulations',
        description: 'Increasing regulatory requirements across multiple jurisdictions require ongoing compliance monitoring and adaptation.',
        impactType: 'compliance',
        impactLevel: 'high',
        likelihood: 'high',
        ismsRelevance: 'Must maintain compliance with GDPR, CCPA, and emerging privacy regulations',
        affectedAreas: ['Legal', 'Information Security', 'Product Development', 'Customer Success'],
        controlImplications: 'Privacy-by-design, data mapping, consent management, breach notification procedures',
        responseStrategy: 'Proactive compliance monitoring and privacy program',
        mitigationActions: ['Regular regulatory scanning', 'Privacy impact assessments', 'DPO engagement'],
        monitoringFrequency: 'monthly',
        lastReviewDate: new Date('2024-10-01'),
        nextReviewDate: new Date('2025-01-01'),
        trendDirection: 'increasing',
        status: 'active',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.contextIssue.create({
      data: {
        issueCode: 'CTX-EXT-002',
        issueType: 'external',
        category: 'threat_landscape',
        title: 'Increasing Sophistication of Cyber Threats',
        description: 'The threat landscape continues to evolve with more sophisticated attacks targeting SaaS providers and their customers.',
        impactType: 'security',
        impactLevel: 'critical',
        likelihood: 'high',
        ismsRelevance: 'Requires continuous improvement of security controls and threat detection capabilities',
        affectedAreas: ['Information Security', 'IT Operations', 'Product Development'],
        controlImplications: 'Advanced threat detection, incident response, security awareness, vulnerability management',
        responseStrategy: 'Defense in depth with continuous monitoring',
        mitigationActions: ['SIEM implementation', 'Threat intelligence', 'Red team exercises', 'Security awareness'],
        monitoringFrequency: 'continuous',
        lastReviewDate: new Date('2024-11-01'),
        nextReviewDate: new Date('2025-02-01'),
        trendDirection: 'increasing',
        status: 'active',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.contextIssue.create({
      data: {
        issueCode: 'CTX-EXT-003',
        issueType: 'external',
        category: 'market',
        title: 'Customer Security Requirements',
        description: 'Enterprise customers increasingly require security certifications and detailed security assessments before procurement.',
        impactType: 'business',
        impactLevel: 'high',
        likelihood: 'high',
        ismsRelevance: 'ISO 27001 certification is becoming a market requirement for enterprise sales',
        affectedAreas: ['Sales', 'Information Security', 'Legal'],
        controlImplications: 'Maintain certifications, streamline security questionnaire responses',
        responseStrategy: 'Achieve and maintain ISO 27001 certification',
        mitigationActions: ['ISO 27001 certification', 'SOC 2 maintenance', 'Security documentation'],
        monitoringFrequency: 'quarterly',
        lastReviewDate: new Date('2024-09-01'),
        nextReviewDate: new Date('2025-03-01'),
        trendDirection: 'stable',
        status: 'active',
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${contextIssues.length} context issues`);

  // Create Interested Parties (ISO 27001 Clause 4.2)
  const interestedParties = await Promise.all([
    prisma.interestedParty.create({
      data: {
        partyCode: 'IP-001',
        name: 'Enterprise Customers',
        partyType: 'customer',
        description: 'Large enterprise customers who use our software solutions',
        expectations: 'Secure, reliable software with strong data protection and compliance certifications',
        requirements: 'ISO 27001 certification, SOC 2 reports, data processing agreements, SLA guarantees',
        informationNeeds: ['Security certifications', 'Incident notifications', 'Compliance reports', 'Security questionnaire responses'],
        powerLevel: 'high',
        interestLevel: 'high',
        influenceLevel: 'high',
        engagementStrategy: 'Regular security updates, dedicated security contacts, proactive communication',
        communicationMethod: 'Email, customer portal, quarterly business reviews',
        communicationFrequency: 'quarterly',
        primaryContact: 'Customer Success Team',
        contactEmail: 'security@acme.com',
        ismsRelevance: 'Primary driver for security certifications and controls',
        securityExpectations: 'Data encryption, access controls, incident response, business continuity',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.interestedParty.create({
      data: {
        partyCode: 'IP-002',
        name: 'Employees',
        partyType: 'internal',
        description: 'All employees and contractors working for the organization',
        expectations: 'Clear security policies, adequate training, secure working environment',
        requirements: 'Security awareness training, clear acceptable use policies, incident reporting channels',
        informationNeeds: ['Security policies', 'Training materials', 'Incident reporting procedures'],
        powerLevel: 'medium',
        interestLevel: 'medium',
        influenceLevel: 'medium',
        engagementStrategy: 'Regular training, clear communication, accessible policies',
        communicationMethod: 'Intranet, email, training sessions',
        communicationFrequency: 'monthly',
        primaryContact: 'HR and Security Team',
        contactEmail: 'hr@acme.com',
        ismsRelevance: 'Key stakeholders in implementing security controls',
        securityExpectations: 'Clear guidance, support for security responsibilities',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.interestedParty.create({
      data: {
        partyCode: 'IP-003',
        name: 'Regulators and Authorities',
        partyType: 'regulator',
        description: 'Data protection authorities and industry regulators',
        expectations: 'Compliance with applicable laws and regulations',
        requirements: 'GDPR compliance, breach notification, registration, audit cooperation',
        informationNeeds: ['Compliance status', 'Breach notifications', 'Audit evidence'],
        powerLevel: 'high',
        interestLevel: 'high',
        influenceLevel: 'high',
        engagementStrategy: 'Proactive compliance, timely reporting, cooperation',
        communicationMethod: 'Official correspondence, regulatory portals',
        communicationFrequency: 'as_required',
        primaryContact: 'Legal and Compliance Team',
        contactEmail: 'legal@acme.com',
        ismsRelevance: 'Define mandatory security and privacy requirements',
        securityExpectations: 'Demonstrable compliance with security obligations',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.interestedParty.create({
      data: {
        partyCode: 'IP-004',
        name: 'Shareholders and Investors',
        partyType: 'shareholder',
        description: 'Company shareholders and investment partners',
        expectations: 'Effective risk management, protection of company assets and reputation',
        requirements: 'Regular risk reporting, security governance, incident disclosure',
        informationNeeds: ['Risk reports', 'Security posture updates', 'Incident summaries'],
        powerLevel: 'high',
        interestLevel: 'medium',
        influenceLevel: 'high',
        engagementStrategy: 'Board reporting, annual security reviews',
        communicationMethod: 'Board meetings, investor reports',
        communicationFrequency: 'quarterly',
        primaryContact: 'Executive Team',
        contactEmail: 'investors@acme.com',
        ismsRelevance: 'Governance oversight of security program',
        securityExpectations: 'Mature security program, risk management',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.interestedParty.create({
      data: {
        partyCode: 'IP-005',
        name: 'Technology Partners',
        partyType: 'partner',
        description: 'Cloud providers, software vendors, and integration partners',
        expectations: 'Secure integrations, compliance with partner security requirements',
        requirements: 'API security, data protection, incident coordination',
        informationNeeds: ['Integration security requirements', 'Incident notifications'],
        powerLevel: 'medium',
        interestLevel: 'medium',
        influenceLevel: 'medium',
        engagementStrategy: 'Regular security reviews, shared responsibility documentation',
        communicationMethod: 'Partner portals, technical contacts',
        communicationFrequency: 'quarterly',
        primaryContact: 'IT and Security Team',
        contactEmail: 'partnerships@acme.com',
        ismsRelevance: 'Third-party risk management and supply chain security',
        securityExpectations: 'Secure development practices, vulnerability management',
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${interestedParties.length} interested parties`);

  // Create Products and Services
  const products = await Promise.all([
    prisma.productService.create({
      data: {
        productCode: 'PROD-001',
        name: 'Enterprise Platform',
        productType: 'saas',
        description: 'Core enterprise software platform for business operations management',
        category: 'Core Product',
        customerFacing: true,
        internalOnly: false,
        revenueContribution: 'primary',
        pricingModel: 'subscription',
        targetMarket: 'Enterprise (1000+ employees)',
        lifecycleStage: 'growth',
        launchDate: new Date('2016-03-01'),
        dataClassification: 'confidential',
        containsPersonalData: true,
        containsSensitiveData: true,
        complianceRequirements: ['GDPR', 'SOC 2', 'ISO 27001'],
        inIsmsScope: true,
        scopeJustification: 'Primary revenue-generating product handling customer data',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.productService.create({
      data: {
        productCode: 'PROD-002',
        name: 'Analytics Dashboard',
        productType: 'saas',
        description: 'Business intelligence and analytics module',
        category: 'Add-on Module',
        customerFacing: true,
        internalOnly: false,
        revenueContribution: 'secondary',
        pricingModel: 'subscription',
        targetMarket: 'Mid-market and Enterprise',
        lifecycleStage: 'mature',
        launchDate: new Date('2018-06-01'),
        dataClassification: 'confidential',
        containsPersonalData: true,
        containsSensitiveData: false,
        complianceRequirements: ['GDPR', 'SOC 2'],
        inIsmsScope: true,
        scopeJustification: 'Processes customer business data',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.productService.create({
      data: {
        productCode: 'PROD-003',
        name: 'Mobile App',
        productType: 'mobile_app',
        description: 'iOS and Android mobile application for platform access',
        category: 'Core Product',
        customerFacing: true,
        internalOnly: false,
        revenueContribution: 'included',
        pricingModel: 'included',
        targetMarket: 'All customers',
        lifecycleStage: 'growth',
        launchDate: new Date('2020-01-15'),
        dataClassification: 'confidential',
        containsPersonalData: true,
        containsSensitiveData: false,
        complianceRequirements: ['GDPR', 'Mobile security standards'],
        inIsmsScope: true,
        scopeJustification: 'Mobile access to platform with customer data',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.productService.create({
      data: {
        productCode: 'SVC-001',
        name: 'Professional Services',
        productType: 'service',
        description: 'Implementation, customization, and consulting services',
        category: 'Services',
        customerFacing: true,
        internalOnly: false,
        revenueContribution: 'secondary',
        pricingModel: 'project_based',
        targetMarket: 'Enterprise customers',
        lifecycleStage: 'mature',
        launchDate: new Date('2016-03-01'),
        dataClassification: 'confidential',
        containsPersonalData: true,
        containsSensitiveData: true,
        complianceRequirements: ['GDPR', 'NDA requirements'],
        inIsmsScope: true,
        scopeJustification: 'Access to customer systems and data during implementation',
        isActive: true,
        createdById: users[0].id,
      },
    }),
    prisma.productService.create({
      data: {
        productCode: 'SVC-002',
        name: 'Customer Support',
        productType: 'service',
        description: '24/7 technical support and customer success services',
        category: 'Services',
        customerFacing: true,
        internalOnly: false,
        revenueContribution: 'included',
        pricingModel: 'included',
        targetMarket: 'All customers',
        lifecycleStage: 'mature',
        launchDate: new Date('2016-03-01'),
        dataClassification: 'confidential',
        containsPersonalData: true,
        containsSensitiveData: false,
        complianceRequirements: ['GDPR'],
        inIsmsScope: true,
        scopeJustification: 'Support staff access customer accounts for troubleshooting',
        isActive: true,
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${products.length} products and services`);

  // Create Technology Platforms
  const platforms = await Promise.all([
    prisma.technologyPlatform.create({
      data: {
        platformCode: 'PLAT-001',
        name: 'AWS Production Environment',
        platformType: 'cloud_infrastructure',
        description: 'Primary production infrastructure hosted on Amazon Web Services',
        vendor: 'Amazon Web Services',
        vendorWebsite: 'https://aws.amazon.com',
        supportContact: 'AWS Enterprise Support',
        licenseType: 'enterprise',
        hostingLocation: 'US-East-1, EU-West-1',
        cloudProvider: 'AWS',
        deploymentModel: 'public_cloud',
        version: 'N/A',
        architecture: 'Microservices on EKS',
        integrations: ['GitHub Actions', 'Datadog', 'PagerDuty'],
        dataStorageLocation: 'US and EU regions',
        criticalityLevel: 'critical',
        businessImpact: 'Complete service outage if unavailable',
        riskRating: 'low',
        implementationDate: new Date('2017-01-01'),
        lastUpgradeDate: new Date('2024-06-01'),
        complianceCertifications: ['SOC 2', 'ISO 27001', 'PCI DSS'],
        dataClassification: 'confidential',
        inIsmsScope: true,
        scopeJustification: 'Hosts all production workloads and customer data',
        isActive: true,
        environments: ['production', 'staging', 'development'],
        createdById: users[0].id,
      },
    }),
    prisma.technologyPlatform.create({
      data: {
        platformCode: 'PLAT-002',
        name: 'GitHub Enterprise',
        platformType: 'development_platform',
        description: 'Source code repository and CI/CD platform',
        vendor: 'GitHub',
        vendorWebsite: 'https://github.com',
        supportContact: 'GitHub Enterprise Support',
        licenseType: 'enterprise',
        hostingLocation: 'GitHub Cloud (US)',
        cloudProvider: 'GitHub',
        deploymentModel: 'saas',
        version: 'Enterprise Cloud',
        architecture: 'SaaS',
        integrations: ['AWS', 'Jira', 'Slack', 'Datadog'],
        dataStorageLocation: 'US',
        criticalityLevel: 'critical',
        businessImpact: 'Development and deployment blocked',
        riskRating: 'low',
        implementationDate: new Date('2018-03-01'),
        lastUpgradeDate: new Date('2024-09-01'),
        complianceCertifications: ['SOC 2', 'ISO 27001'],
        dataClassification: 'confidential',
        inIsmsScope: true,
        scopeJustification: 'Contains all source code and deployment pipelines',
        isActive: true,
        environments: ['production'],
        createdById: users[0].id,
      },
    }),
    prisma.technologyPlatform.create({
      data: {
        platformCode: 'PLAT-003',
        name: 'Okta Identity Platform',
        platformType: 'identity_management',
        description: 'Identity and access management for employees and applications',
        vendor: 'Okta',
        vendorWebsite: 'https://www.okta.com',
        supportContact: 'Okta Support',
        licenseType: 'enterprise',
        hostingLocation: 'Okta Cloud (US)',
        cloudProvider: 'Okta',
        deploymentModel: 'saas',
        version: 'Enterprise',
        architecture: 'SaaS',
        integrations: ['AWS', 'GitHub', 'Salesforce', 'All SaaS apps'],
        dataStorageLocation: 'US',
        criticalityLevel: 'critical',
        businessImpact: 'Users cannot authenticate',
        riskRating: 'low',
        implementationDate: new Date('2019-06-01'),
        lastUpgradeDate: new Date('2024-08-01'),
        complianceCertifications: ['SOC 2', 'ISO 27001', 'FedRAMP'],
        dataClassification: 'confidential',
        inIsmsScope: true,
        scopeJustification: 'Central identity provider for all systems',
        isActive: true,
        environments: ['production'],
        createdById: users[0].id,
      },
    }),
    prisma.technologyPlatform.create({
      data: {
        platformCode: 'PLAT-004',
        name: 'PostgreSQL Database Cluster',
        platformType: 'database',
        description: 'Primary relational database for application data',
        vendor: 'PostgreSQL / AWS RDS',
        vendorWebsite: 'https://www.postgresql.org',
        supportContact: 'AWS RDS Support',
        licenseType: 'open_source',
        hostingLocation: 'AWS RDS Multi-AZ',
        cloudProvider: 'AWS',
        deploymentModel: 'managed_service',
        version: '15.4',
        architecture: 'Multi-AZ with read replicas',
        integrations: ['Application servers', 'Analytics platform'],
        dataStorageLocation: 'US-East-1, EU-West-1',
        criticalityLevel: 'critical',
        businessImpact: 'Application unavailable, data loss risk',
        riskRating: 'low',
        implementationDate: new Date('2017-01-01'),
        lastUpgradeDate: new Date('2024-03-01'),
        nextUpgradeDate: new Date('2025-03-01'),
        complianceCertifications: ['SOC 2', 'ISO 27001'],
        dataClassification: 'confidential',
        inIsmsScope: true,
        scopeJustification: 'Stores all customer and application data',
        isActive: true,
        environments: ['production', 'staging', 'development'],
        createdById: users[0].id,
      },
    }),
    prisma.technologyPlatform.create({
      data: {
        platformCode: 'PLAT-005',
        name: 'Datadog Monitoring',
        platformType: 'monitoring',
        description: 'Application performance monitoring and logging platform',
        vendor: 'Datadog',
        vendorWebsite: 'https://www.datadoghq.com',
        supportContact: 'Datadog Support',
        licenseType: 'enterprise',
        hostingLocation: 'Datadog Cloud (US)',
        cloudProvider: 'Datadog',
        deploymentModel: 'saas',
        version: 'Enterprise',
        architecture: 'SaaS',
        integrations: ['AWS', 'Kubernetes', 'GitHub', 'PagerDuty'],
        dataStorageLocation: 'US',
        criticalityLevel: 'high',
        businessImpact: 'Reduced visibility into system health',
        riskRating: 'low',
        implementationDate: new Date('2019-01-01'),
        lastUpgradeDate: new Date('2024-10-01'),
        complianceCertifications: ['SOC 2', 'ISO 27001'],
        dataClassification: 'internal',
        inIsmsScope: true,
        scopeJustification: 'Contains application logs and metrics',
        isActive: true,
        environments: ['production', 'staging'],
        createdById: users[0].id,
      },
    }),
  ]);
  console.log(`✅ Created ${platforms.length} technology platforms`);

  // Seed Incident Management Reference Data
  try {
    const { seedIncidents } = await import('./seed/incidents/seed-incidents');
    await seedIncidents();
  } catch (e) {
    console.warn('⚠️  Incidents seed skipped:', (e as Error).message);
  }

  // Seed control testing demo data (layers, tests from templates, sample executions)
  try {
    const { seedControlTestingDemo } = await import('./seed/controls/seed-control-testing-demo');
    await seedControlTestingDemo();
  } catch (e) {
    console.warn('⚠️  Control testing demo seed skipped:', (e as Error).message);
  }

  // Seed control activities
  try {
    const { seedControlActivities } = await import('./seed/controls/seed-control-activities');
    await seedControlActivities(prisma);
    console.log('✅ Seeded control activities');
  } catch (e) {
    console.warn('⚠️  Control activities seed skipped:', (e as Error).message);
  }

  // Seed Risks, Scenarios, and KRIs
  try {
    const { seedRisks } = await import('./seed/risks/seed-risks');
    await seedRisks();
  } catch (e) {
    console.warn('⚠️  Risks seed skipped:', (e as Error).message);
  }

  // Seed ClearStream Payments demo data
  await seedDemo();

  console.log('\n🎉 Database seed completed successfully!');
  console.log('\n📋 Summary:');
  console.log(`   - ${users.length} users`);
  console.log(`   - 1 organisation profile`);
  console.log(`   - ${locations.length} locations`);
  console.log(`   - ${departments.length} departments`);
  console.log(`   - ${processes.length} business processes`);
  console.log(`   - ${dependencies.length} external dependencies`);
  console.log(`   - ${regulators.length} regulators`);
  console.log(`   - 1 security committee with ${memberships.length} members`);
  console.log(`   - 1 meeting with ${decisions.length} decisions and ${actionItems.length} action items`);
  console.log(`   - ${executives.length} executive positions`);
  console.log(`   - ${champions.length} security champions`);
  console.log(`   - 37 survey questions (15 DORA + 22 NIS2)`);
  console.log(`   - ${keyPersonnel.length} key personnel`);
  console.log(`   - ${frameworks.length} applicable frameworks`);
  console.log(`   - ${contextIssues.length} context issues`);
  console.log(`   - ${interestedParties.length} interested parties`);
  console.log(`   - ${products.length} products and services`);
  console.log(`   - ${platforms.length} technology platforms`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
